In [1]:
import pandas as pd
import numpy as np 
import os

In [2]:
df = pd.read_csv("./Datas/DEF_IMMO.csv", index_col=0)
df.head(5)

,type_of_property,subtype_of_property,locality,province,région,price,number_of_facades,house_area,house_area_cat,number_of_rooms,...,fully_equipped_kitchen,garden,garden_area,terrace,terrace_area,open_fire,swimming_pool,state_of_the_building,construction_year,construction_year_cat
0,house,house,1050,Bruxelles-Capitale,Région Bruxelles-capitale,340000,2.0,203.0,]180-240 m²],6,...,1,0,NaN,1,NaN,0,0,to be done up,1901.0,1900-1919
1,house,villa,1880,Brabant flamand,Région flamande,525000,4.0,250.0,]240m²- ],6,...,1,1,430.0,1,40.0,0,0,as new,1992.0,1980-1999
2,house,exceptional property,4900,Liège,Région wallonne,550000,4.0,475.0,]240m²- ],11,...,1,1,1400.0,1,NaN,0,0,good,1853.0,older than 1900
3,house,villa,7912,Hainaut,Région wallonne,550000,4.0,325.0,]240m²- ],4,...,1,1,2333.0,1,NaN,0,0,good,1918.0,1900-1919
4,house,house,6032,Hainaut,Région wallonne,550000,3.0,400.0,]240m²- ],5,...,1,1,500.0,1,80.0,0,0,as new,1977.0,1960-1979

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 42352 entries, 0 to 42351
Data columns (total 23 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   type_of_property         42352 non-null  object
 1   subtype_of_property      42352 non-null  object
 2   locality                 42352 non-null  int64
 3   province                 42352 non-null  object
 4   région                   42352 non-null  object
 5   price                    42352 non-null  int64
 6   number_of_facades        31708 non-null  float64
 7   house_area               42225 non-null  float64
 8   house_area_cat           42225 non-null  object
 9   number_of_rooms          42352 non-null  int64
 10  number_of_rooms_cat      42352 non-null  object
 11  surface_of_the_land      22365 non-null  float64
 12  surface_of_the_land_cat  22365 non-null  object
 13  fully_equipped_kitchen   42352 non-null  int64
 14  garden                   42352 non-null  int64
 15  garden_area              7864 non-null   float64
 16  terrace                  42352 non-null  int64
 17  terrace_area             16295 non-null  float64
 18  open_fire                42352 non-null  int64
 19  swimming_pool            42352 non-null  int64
 20  state_of_the_building    32096 non-null  object
 21  construction_year        26136 non-null  float64
 22  construction_year_cat    26136 non-null  object
dtypes: float64(6), int64(8), object(9)
memory usage: 7.8+ MB

In [4]:
df.isnull().sum()

type_of_property               0
subtype_of_property            0
locality                       0
province                       0
région                         0
price                          0
number_of_facades          10644
house_area                   127
house_area_cat               127
number_of_rooms                0
number_of_rooms_cat            0
surface_of_the_land        19987
surface_of_the_land_cat    19987
fully_equipped_kitchen         0
garden                         0
garden_area                34488
terrace                        0
terrace_area               26057
open_fire                      0
swimming_pool                  0
state_of_the_building      10256
construction_year          16216
construction_year_cat      16216
dtype: int64

In [5]:
# drop the house/apartment without area
df.dropna(axis=0, inplace=True, subset=['house_area'])
df.isnull().sum()

type_of_property               0
subtype_of_property            0
locality                       0
province                       0
région                         0
price                          0
number_of_facades          10627
house_area                     0
house_area_cat                 0
number_of_rooms                0
number_of_rooms_cat            0
surface_of_the_land        19987
surface_of_the_land_cat    19987
fully_equipped_kitchen         0
garden                         0
garden_area                34382
terrace                        0
terrace_area               25944
open_fire                      0
swimming_pool                  0
state_of_the_building      10224
construction_year          16143
construction_year_cat      16143
dtype: int64

### Features Exploration and removing outliers

In [6]:
df.house_area.describe()

count    42225.000000
mean       151.293025
std         89.341495
min         11.000000
25%         90.000000
50%        129.000000
75%        185.000000
max        710.000000
Name: house_area, dtype: float64

In [7]:
df.price.describe()

count     42225.000000
mean     312723.382664
std      169249.397037
min        2500.000000
25%      199000.000000
50%      270000.000000
75%      379000.000000
max      950000.000000
Name: price, dtype: float64

In [8]:
df['price'].sort_values(ascending=True).head(20)
mask = df['price']<25000
df.loc[mask]

,type_of_property,subtype_of_property,locality,province,région,price,number_of_facades,house_area,house_area_cat,number_of_rooms,...,fully_equipped_kitchen,garden,garden_area,terrace,terrace_area,open_fire,swimming_pool,state_of_the_building,construction_year,construction_year_cat
24,house,house,4540,Liège,Région wallonne,20000,2.0,115.0,]60-120 m²],2,...,1,1,145.0,1,NaN,0,0,to be done up,1874.0,older than 1900
36,house,house,5580,Namur,Région wallonne,15000,4.0,130.0,]120-180 m²],2,...,1,1,420.0,1,24.0,1,0,good,1974.0,1960-1979
81,house,house,4000,Liège,Région wallonne,20000,2.0,90.0,]60-120 m²],2,...,1,1,75.0,1,15.0,0,0,good,NaN,NaN
94,house,town house,4101,Liège,Région wallonne,20000,2.0,110.0,]60-120 m²],3,...,0,0,NaN,0,NaN,0,0,as new,1973.0,1960-1979
95,house,house,7334,Hainaut,Région wallonne,20000,2.0,140.0,]120-180 m²],3,...,0,0,NaN,0,NaN,0,0,good,1925.0,1920-1939
105,house,house,6900,Luxembourg,Région wallonne,10000,2.0,145.0,]120-180 m²],3,...,1,1,174.0,1,NaN,0,0,good,NaN,NaN
131,house,house,6511,Hainaut,Région wallonne,20000,3.0,85.0,]60-120 m²],2,...,1,0,NaN,0,NaN,0,0,as new,NaN,NaN
276,house,house,5030,Namur,Région wallonne,10000,4.0,110.0,]60-120 m²],2,...,1,0,NaN,0,NaN,0,0,good,NaN,NaN
307,house,house,7090,Hainaut,Région wallonne,15000,3.0,113.0,]60-120 m²],3,...,1,1,NaN,0,NaN,0,0,good,NaN,NaN
308,house,house,6061,Hainaut,Région wallonne,15000,3.0,85.0,]60-120 m²],2,...,1,0,NaN,0,NaN,0,0,good,NaN,NaN
483,house,house,7160,Hainaut,Région wallonne,19000,2.0,150.0,]120-180 m²],2,...,1,0,NaN,0,NaN,0,0,good,1896.0,older than 1900
602,house,house,4420,Liège,Région wallonne,10000,2.0,178.0,]120-180 m²],4,...,1,1,30.0,0,NaN,0,0,NaN,NaN,NaN
617,house,house,7060,Hainaut,Région wallonne,24000,3.0,179.0,]120-180 m²],3,...,1,1,NaN,1,NaN,1,0,as new,1900.0,1900-1919
699,house,mixed use building,6032,Hainaut,Région wallonne,12500,3.0,170.0,]120-180 m²],4,...,0,0,NaN,0,NaN,0,0,good,1950.0,1940-1959
711,house,house,7090,Hainaut,Région wallonne,15000,3.0,115.0,]60-120 m²],2,...,1,1,NaN,1,NaN,0,0,good,1933.0,1920-1939
712,house,house,2840,Anvers,Région flamande,15000,NaN,115.0,]60-120 m²],2,...,0,1,NaN,1,30.0,0,0,as new,1970.0,1960-1979
743,house,house,5300,Namur,Région wallonne,15000,2.0,100.0,]60-120 m²],2,...,1,1,NaN,0,NaN,0,0,good,NaN,NaN
3668,apartment,apartment,6180,Hainaut,Région wallonne,20000,3.0,115.0,]60-120 m²],1,...,1,1,80.0,0,NaN,0,0,good,NaN,NaN
3685,apartment,apartment,1400,Brabant wallon,Région wallonne,2500,4.0,90.0,]60-120 m²],3,...,1,0,NaN,1,4.0,0,0,as new,1978.0,1960-1979
3686,apartment,kot,6740,Luxembourg,Région wallonne,14500,4.0,28.0,[0-60 m²],1,...,1,0,NaN,0,NaN,0,0,good,2015.0,2000-
3692,apartment,flat studio,8301,Flandre-Occidentale,Région flamande,20000,2.0,42.0,[0-60 m²],0,...,0,0,NaN,0,NaN,0,1,to renovate,1971.0,1960-1979
3695,apartment,apartment,9310,Flandre-Orientale,Région flamande,8160,NaN,100.0,]60-120 m²],2,...,1,0,NaN,0,NaN,0,0,good,NaN,NaN
3696,apartment,apartment,9310,Flandre-Orientale,Région flamande,6600,NaN,100.0,]60-120 m²],3,...,0,0,NaN,0,NaN,0,0,good,NaN,NaN
23538,house,exceptional property,2530,Anvers,Région flamande,2500,4.0,600.0,]240m²- ],5,...,1,1,1750.0,1,60.0,1,0,as new,1842.0,older than 1900
23542,house,house,6000,Hainaut,Région wallonne,10000,2.0,210.0,]180-240 m²],4,...,1,1,NaN,0,NaN,0,0,to be done up,NaN,NaN
23544,house,house,6150,Hainaut,Région wallonne,20000,3.0,125.0,]120-180 m²],3,...,1,1,NaN,0,NaN,0,0,as new,NaN,NaN
23561,house,pavilion,8670,Flandre-Occidentale,Région flamande,19900,4.0,35.0,[0-60 m²],2,...,1,1,50.0,1,7.0,0,0,just renovated,2007.0,2000-
23567,house,house,6464,Hainaut,Région wallonne,9999,4.0,20.0,[0-60 m²],2,...,1,1,180.0,1,7.0,0,0,good,NaN,NaN
23578,house,house,6464,Hainaut,Région wallonne,20000,4.0,45.0,[0-60 m²],2,...,1,1,120.0,1,15.0,0,0,NaN,NaN,NaN
23582,house,other property,6960,Luxembourg,Région wallonne,2500,4.0,154.0,]120-180 m²],3,...,1,1,3000.0,1,18.0,1,0,as new,2006.0,2000-
23587,house,house,3111,Brabant flamand,Région flamande,11825,2.0,13.0,[0-60 m²],1,...,0,0,NaN,0,NaN,0,0,as new,2017.0,2000-

In [9]:
# Creating price / m² feature 
df['price_per_m²'] = round(df['price']/df['house_area'], 2)
df['price_per_m²'].describe()

count    42225.000000
mean      2355.876688
std       1232.912269
min          4.170000
25%       1568.490000
50%       2185.190000
75%       2853.500000
max      45550.000000
Name: price_per_m², dtype: float64

In [10]:
mask = df['price']>900000
df[['price','house_area','price_per_m²','subtype_of_property', 'province']].loc[mask].sort_values(by='price', ascending=False)

,price,house_area,price_per_m²,subtype_of_property,province
3639,950000,200.0,4750.00,mixed use building,Bruxelles-Capitale
23456,950000,365.0,2602.74,triplex,Bruxelles-Capitale
23451,950000,217.0,4377.88,apartment,Bruxelles-Capitale
3663,950000,500.0,1900.00,mansion,Anvers
3660,950000,277.0,3429.60,house,Flandre-Occidentale
...,...,...,...,...,...
3664,910000,424.0,2146.23,house,Flandre-Orientale
23448,910000,171.0,5321.64,penthouse,Bruxelles-Capitale
23449,910000,171.0,5321.64,penthouse,Bruxelles-Capitale
3578,907500,222.0,4087.84,house,Anvers
23473,904500,132.0,6852.27,apartment,Bruxelles-Capitale

In [11]:
# drop all property with a price < 25000
df = df.drop(df[df['price']<25000].index)
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 42194 entries, 0 to 42351
Data columns (total 24 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   type_of_property         42194 non-null  object
 1   subtype_of_property      42194 non-null  object
 2   locality                 42194 non-null  int64
 3   province                 42194 non-null  object
 4   région                   42194 non-null  object
 5   price                    42194 non-null  int64
 6   number_of_facades        31570 non-null  float64
 7   house_area               42194 non-null  float64
 8   house_area_cat           42194 non-null  object
 9   number_of_rooms          42194 non-null  int64
 10  number_of_rooms_cat      42194 non-null  object
 11  surface_of_the_land      22213 non-null  float64
 12  surface_of_the_land_cat  22213 non-null  object
 13  fully_equipped_kitchen   42194 non-null  int64
 14  garden                   42194 non-null  int64
 15  garden_area              7832 non-null   float64
 16  terrace                  42194 non-null  int64
 17  terrace_area             16272 non-null  float64
 18  open_fire                42194 non-null  int64
 19  swimming_pool            42194 non-null  int64
 20  state_of_the_building    31972 non-null  object
 21  construction_year        26066 non-null  float64
 22  construction_year_cat    26066 non-null  object
 23  price_per_m²             42194 non-null  float64
dtypes: float64(7), int64(8), object(9)
memory usage: 8.0+ MB

In [12]:
mask = df['price_per_m²']<600
df[['price','house_area','price_per_m²','subtype_of_property', 'province']].loc[mask].sort_values(by='price_per_m²', ascending=True)

        price  house_area  price_per_m² subtype_of_property           province
55      25000       270.0         92.59               house              Liège
844     30000       236.0        127.12               house              Namur
762     25000       195.0        128.21               house            Hainaut
184     25000       185.0        135.14               house              Liège
246     25000       182.0        137.36               house              Namur
...       ...         ...           ...                 ...                ...
26138  119000       200.0        595.00               house  Flandre-Orientale
24691  119000       200.0        595.00               house              Namur
24171  100000       168.0        595.24               house              Liège
24495  125000       209.0        598.09               house         Luxembourg
26095  149900       250.0        599.60               house         Luxembourg

[589 rows x 5 columns]

In [13]:
df = df.drop(df[(df['price']<180000)  & (df['house_area']>400)].index)
# mask[['price','house_area','price_per_m²','subtype_of_property', 'province']].sort_values(by='price', ascending=False)
df

,type_of_property,subtype_of_property,locality,province,région,price,number_of_facades,house_area,house_area_cat,number_of_rooms,...,garden,garden_area,terrace,terrace_area,open_fire,swimming_pool,state_of_the_building,construction_year,construction_year_cat,price_per_m²
0,house,house,1050,Bruxelles-Capitale,Région Bruxelles-capitale,340000,2.0,203.0,]180-240 m²],6,...,0,NaN,1,NaN,0,0,to be done up,1901.0,1900-1919,1674.88
1,house,villa,1880,Brabant flamand,Région flamande,525000,4.0,250.0,]240m²- ],6,...,1,430.0,1,40.0,0,0,as new,1992.0,1980-1999,2100.00
2,house,exceptional property,4900,Liège,Région wallonne,550000,4.0,475.0,]240m²- ],11,...,1,1400.0,1,NaN,0,0,good,1853.0,older than 1900,1157.89
3,house,villa,7912,Hainaut,Région wallonne,550000,4.0,325.0,]240m²- ],4,...,1,2333.0,1,NaN,0,0,good,1918.0,1900-1919,1692.31
4,house,house,6032,Hainaut,Région wallonne,550000,3.0,400.0,]240m²- ],5,...,1,500.0,1,80.0,0,0,as new,1977.0,1960-1979,1375.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42347,house,house,2310,Anvers,Région flamande,468000,4.0,180.0,]120-180 m²],3,...,0,NaN,0,NaN,0,0,NaN,NaN,NaN,2600.00
42348,house,house,1800,Brabant flamand,Région flamande,454993,3.0,169.0,]120-180 m²],3,...,0,NaN,0,NaN,0,0,NaN,NaN,NaN,2692.27
42349,house,villa,3530,Limbourg,Région flamande,475000,4.0,222.0,]180-240 m²],3,...,0,NaN,0,NaN,0,0,NaN,NaN,NaN,2139.64
42350,house,mansion,6700,Luxembourg,Région wallonne,475000,2.0,240.0,]180-240 m²],9,...,0,NaN,0,NaN,0,0,NaN,NaN,NaN,1979.17
42351,house,house,2018,Anvers,Région flamande,488000,3.0,145.0,]120-180 m²],3,...,1,48.0,0,NaN,0,0,NaN,NaN,NaN,3365.52

In [14]:
mask = df['price_per_m²']<350
df[['price','house_area','price_per_m²','subtype_of_property', 'province']].loc[mask]

        price  house_area  price_per_m² subtype_of_property  province
55      25000       270.0         92.59               house     Liège
66      25000       146.0        171.23               house   Hainaut
72      37500       200.0        187.50               house     Liège
101     50000       160.0        312.50               house     Liège
116     60000       280.0        214.29               villa   Hainaut
...       ...         ...           ...                 ...       ...
25736  108000       330.0        327.27  mixed use building   Hainaut
25937  132500       395.0        335.44               house  Limbourg
26291  199000       597.0        333.33               house     Namur
26371  199000       600.0        331.67               house     Liège
29498  220000       682.0        322.58           farmhouse   Hainaut

[118 rows x 5 columns]

In [15]:
df = df.drop(df[df['price_per_m²']<350].index)
df

,type_of_property,subtype_of_property,locality,province,région,price,number_of_facades,house_area,house_area_cat,number_of_rooms,...,garden,garden_area,terrace,terrace_area,open_fire,swimming_pool,state_of_the_building,construction_year,construction_year_cat,price_per_m²
0,house,house,1050,Bruxelles-Capitale,Région Bruxelles-capitale,340000,2.0,203.0,]180-240 m²],6,...,0,NaN,1,NaN,0,0,to be done up,1901.0,1900-1919,1674.88
1,house,villa,1880,Brabant flamand,Région flamande,525000,4.0,250.0,]240m²- ],6,...,1,430.0,1,40.0,0,0,as new,1992.0,1980-1999,2100.00
2,house,exceptional property,4900,Liège,Région wallonne,550000,4.0,475.0,]240m²- ],11,...,1,1400.0,1,NaN,0,0,good,1853.0,older than 1900,1157.89
3,house,villa,7912,Hainaut,Région wallonne,550000,4.0,325.0,]240m²- ],4,...,1,2333.0,1,NaN,0,0,good,1918.0,1900-1919,1692.31
4,house,house,6032,Hainaut,Région wallonne,550000,3.0,400.0,]240m²- ],5,...,1,500.0,1,80.0,0,0,as new,1977.0,1960-1979,1375.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42347,house,house,2310,Anvers,Région flamande,468000,4.0,180.0,]120-180 m²],3,...,0,NaN,0,NaN,0,0,NaN,NaN,NaN,2600.00
42348,house,house,1800,Brabant flamand,Région flamande,454993,3.0,169.0,]120-180 m²],3,...,0,NaN,0,NaN,0,0,NaN,NaN,NaN,2692.27
42349,house,villa,3530,Limbourg,Région flamande,475000,4.0,222.0,]180-240 m²],3,...,0,NaN,0,NaN,0,0,NaN,NaN,NaN,2139.64
42350,house,mansion,6700,Luxembourg,Région wallonne,475000,2.0,240.0,]180-240 m²],9,...,0,NaN,0,NaN,0,0,NaN,NaN,NaN,1979.17
42351,house,house,2018,Anvers,Région flamande,488000,3.0,145.0,]120-180 m²],3,...,1,48.0,0,NaN,0,0,NaN,NaN,NaN,3365.52

In [16]:
df[['price','house_area','price_per_m²','subtype_of_property', 'type_of_property','province']].sort_values(by='price_per_m²', ascending=False).head(50)

,price,house_area,price_per_m²,subtype_of_property,type_of_property,province
3661,911000,20.0,45550.00,other property,house,Brabant flamand
42282,500000,18.0,27777.78,house,house,Flandre-Occidentale
16729,297500,13.0,22884.62,penthouse,apartment,Flandre-Orientale
40159,425000,21.0,20238.10,villa,house,Brabant flamand
20417,363000,18.0,20166.67,kot,apartment,Anvers
7416,185000,11.0,16818.18,apartment,apartment,Liège
21499,485000,34.0,14264.71,flat studio,apartment,Flandre-Occidentale
22881,690000,52.0,13269.23,penthouse,apartment,Flandre-Occidentale
23370,879000,70.0,12557.14,apartment,apartment,Flandre-Occidentale
8266,199000,16.0,12437.50,kot,apartment,Brabant flamand
21358,485000,39.0,12435.90,apartment,apartment,Flandre-Occidentale
23373,895000,75.0,11933.33,apartment,apartment,Flandre-Occidentale
6641,179000,15.0,11933.33,flat studio,apartment,Brabant flamand
23308,845000,71.0,11901.41,apartment,apartment,Flandre-Occidentale
23098,765000,65.0,11769.23,apartment,apartment,Flandre-Occidentale
21458,485000,42.0,11547.62,apartment,apartment,Flandre-Occidentale
23481,950000,83.0,11445.78,apartment,apartment,Flandre-Occidentale
6472,181000,16.0,11312.50,flat studio,apartment,Brabant flamand
23311,845000,75.0,11266.67,apartment,apartment,Flandre-Occidentale
23284,845000,75.0,11266.67,apartment,apartment,Flandre-Occidentale
23405,890000,79.0,11265.82,penthouse,apartment,Flandre-Occidentale
23409,890000,79.0,11265.82,apartment,apartment,Flandre-Occidentale
34749,278000,25.0,11120.00,house,house,Flandre-Orientale
23452,945000,85.0,11117.65,apartment,apartment,Flandre-Occidentale
23477,945000,86.0,10988.37,apartment,apartment,Flandre-Occidentale
22368,595000,55.0,10818.18,apartment,apartment,Flandre-Occidentale
22215,595000,55.0,10818.18,apartment,apartment,Flandre-Occidentale
22242,595000,55.0,10818.18,apartment,apartment,Flandre-Occidentale
23330,850000,80.0,10625.00,apartment,apartment,Flandre-Occidentale
23412,899000,85.0,10576.47,apartment,apartment,Flandre-Occidentale
8923,169000,16.0,10562.50,flat studio,apartment,Brabant flamand
23369,875000,83.0,10542.17,apartment,apartment,Flandre-Occidentale
23461,945000,90.0,10500.00,apartment,apartment,Flandre-Occidentale
22948,745000,71.0,10492.96,duplex,apartment,Flandre-Occidentale
22959,745000,71.0,10492.96,apartment,apartment,Flandre-Occidentale
23255,849000,81.0,10481.48,apartment,apartment,Flandre-Occidentale
23298,849000,81.0,10481.48,apartment,apartment,Flandre-Occidentale
23258,849000,81.0,10481.48,apartment,apartment,Flandre-Occidentale
23285,849000,81.0,10481.48,apartment,apartment,Flandre-Occidentale
23511,920000,88.0,10454.55,apartment,apartment,Flandre-Occidentale
23248,845000,81.0,10432.10,apartment,apartment,Flandre-Occidentale
23302,849000,82.0,10353.66,apartment,apartment,Flandre-Occidentale
23320,849000,82.0,10353.66,apartment,apartment,Flandre-Occidentale
23273,849000,82.0,10353.66,apartment,apartment,Flandre-Occidentale
23327,849000,82.0,10353.66,apartment,apartment,Flandre-Occidentale
23328,849000,82.0,10353.66,apartment,apartment,Flandre-Occidentale
23267,849000,82.0,10353.66,apartment,apartment,Flandre-Occidentale
23260,849000,82.0,10353.66,apartment,apartment,Flandre-Occidentale
23280,849000,82.0,10353.66,apartment,apartment,Flandre-Occidentale
23324,849000,82.0,10353.66,apartment,apartment,Flandre-Occidentale

In [17]:
df = df.drop(df[(df['price_per_m²']>10000)  & (df['type_of_property']=='house')].index)
df

,type_of_property,subtype_of_property,locality,province,région,price,number_of_facades,house_area,house_area_cat,number_of_rooms,...,garden,garden_area,terrace,terrace_area,open_fire,swimming_pool,state_of_the_building,construction_year,construction_year_cat,price_per_m²
0,house,house,1050,Bruxelles-Capitale,Région Bruxelles-capitale,340000,2.0,203.0,]180-240 m²],6,...,0,NaN,1,NaN,0,0,to be done up,1901.0,1900-1919,1674.88
1,house,villa,1880,Brabant flamand,Région flamande,525000,4.0,250.0,]240m²- ],6,...,1,430.0,1,40.0,0,0,as new,1992.0,1980-1999,2100.00
2,house,exceptional property,4900,Liège,Région wallonne,550000,4.0,475.0,]240m²- ],11,...,1,1400.0,1,NaN,0,0,good,1853.0,older than 1900,1157.89
3,house,villa,7912,Hainaut,Région wallonne,550000,4.0,325.0,]240m²- ],4,...,1,2333.0,1,NaN,0,0,good,1918.0,1900-1919,1692.31
4,house,house,6032,Hainaut,Région wallonne,550000,3.0,400.0,]240m²- ],5,...,1,500.0,1,80.0,0,0,as new,1977.0,1960-1979,1375.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42347,house,house,2310,Anvers,Région flamande,468000,4.0,180.0,]120-180 m²],3,...,0,NaN,0,NaN,0,0,NaN,NaN,NaN,2600.00
42348,house,house,1800,Brabant flamand,Région flamande,454993,3.0,169.0,]120-180 m²],3,...,0,NaN,0,NaN,0,0,NaN,NaN,NaN,2692.27
42349,house,villa,3530,Limbourg,Région flamande,475000,4.0,222.0,]180-240 m²],3,...,0,NaN,0,NaN,0,0,NaN,NaN,NaN,2139.64
42350,house,mansion,6700,Luxembourg,Région wallonne,475000,2.0,240.0,]180-240 m²],9,...,0,NaN,0,NaN,0,0,NaN,NaN,NaN,1979.17
42351,house,house,2018,Anvers,Région flamande,488000,3.0,145.0,]120-180 m²],3,...,1,48.0,0,NaN,0,0,NaN,NaN,NaN,3365.52

In [18]:
df['number_of_rooms'].describe()
df['number_of_rooms'].sort_values(ascending=False).head(20)

22650    204
22649    204
22639    204
24822    165
39664     23
3215      22
41815     18
1279      16
38520     16
38519     16
1657      16
39709     16
42203     15
34848     15
1777      15
35967     14
2883      14
2261      14
2291      14
31895     13
Name: number_of_rooms, dtype: int64

In [19]:
df = df.drop(df[df['number_of_rooms']>25].index)
df

,type_of_property,subtype_of_property,locality,province,région,price,number_of_facades,house_area,house_area_cat,number_of_rooms,...,garden,garden_area,terrace,terrace_area,open_fire,swimming_pool,state_of_the_building,construction_year,construction_year_cat,price_per_m²
0,house,house,1050,Bruxelles-Capitale,Région Bruxelles-capitale,340000,2.0,203.0,]180-240 m²],6,...,0,NaN,1,NaN,0,0,to be done up,1901.0,1900-1919,1674.88
1,house,villa,1880,Brabant flamand,Région flamande,525000,4.0,250.0,]240m²- ],6,...,1,430.0,1,40.0,0,0,as new,1992.0,1980-1999,2100.00
2,house,exceptional property,4900,Liège,Région wallonne,550000,4.0,475.0,]240m²- ],11,...,1,1400.0,1,NaN,0,0,good,1853.0,older than 1900,1157.89
3,house,villa,7912,Hainaut,Région wallonne,550000,4.0,325.0,]240m²- ],4,...,1,2333.0,1,NaN,0,0,good,1918.0,1900-1919,1692.31
4,house,house,6032,Hainaut,Région wallonne,550000,3.0,400.0,]240m²- ],5,...,1,500.0,1,80.0,0,0,as new,1977.0,1960-1979,1375.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42347,house,house,2310,Anvers,Région flamande,468000,4.0,180.0,]120-180 m²],3,...,0,NaN,0,NaN,0,0,NaN,NaN,NaN,2600.00
42348,house,house,1800,Brabant flamand,Région flamande,454993,3.0,169.0,]120-180 m²],3,...,0,NaN,0,NaN,0,0,NaN,NaN,NaN,2692.27
42349,house,villa,3530,Limbourg,Région flamande,475000,4.0,222.0,]180-240 m²],3,...,0,NaN,0,NaN,0,0,NaN,NaN,NaN,2139.64
42350,house,mansion,6700,Luxembourg,Région wallonne,475000,2.0,240.0,]180-240 m²],9,...,0,NaN,0,NaN,0,0,NaN,NaN,NaN,1979.17
42351,house,house,2018,Anvers,Région flamande,488000,3.0,145.0,]120-180 m²],3,...,1,48.0,0,NaN,0,0,NaN,NaN,NaN,3365.52

In [20]:
# reseting the index 
df.reset_index(inplace=True)
df

,index,type_of_property,subtype_of_property,locality,province,région,price,number_of_facades,house_area,house_area_cat,...,garden,garden_area,terrace,terrace_area,open_fire,swimming_pool,state_of_the_building,construction_year,construction_year_cat,price_per_m²
0,0,house,house,1050,Bruxelles-Capitale,Région Bruxelles-capitale,340000,2.0,203.0,]180-240 m²],...,0,NaN,1,NaN,0,0,to be done up,1901.0,1900-1919,1674.88
1,1,house,villa,1880,Brabant flamand,Région flamande,525000,4.0,250.0,]240m²- ],...,1,430.0,1,40.0,0,0,as new,1992.0,1980-1999,2100.00
2,2,house,exceptional property,4900,Liège,Région wallonne,550000,4.0,475.0,]240m²- ],...,1,1400.0,1,NaN,0,0,good,1853.0,older than 1900,1157.89
3,3,house,villa,7912,Hainaut,Région wallonne,550000,4.0,325.0,]240m²- ],...,1,2333.0,1,NaN,0,0,good,1918.0,1900-1919,1692.31
4,4,house,house,6032,Hainaut,Région wallonne,550000,3.0,400.0,]240m²- ],...,1,500.0,1,80.0,0,0,as new,1977.0,1960-1979,1375.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42053,42347,house,house,2310,Anvers,Région flamande,468000,4.0,180.0,]120-180 m²],...,0,NaN,0,NaN,0,0,NaN,NaN,NaN,2600.00
42054,42348,house,house,1800,Brabant flamand,Région flamande,454993,3.0,169.0,]120-180 m²],...,0,NaN,0,NaN,0,0,NaN,NaN,NaN,2692.27
42055,42349,house,villa,3530,Limbourg,Région flamande,475000,4.0,222.0,]180-240 m²],...,0,NaN,0,NaN,0,0,NaN,NaN,NaN,2139.64
42056,42350,house,mansion,6700,Luxembourg,Région wallonne,475000,2.0,240.0,]180-240 m²],...,0,NaN,0,NaN,0,0,NaN,NaN,NaN,1979.17
42057,42351,house,house,2018,Anvers,Région flamande,488000,3.0,145.0,]120-180 m²],...,1,48.0,0,NaN,0,0,NaN,NaN,NaN,3365.52

### Group by locality into Commune

In [21]:
'''Get the dataset of Communes by postal code here :
https://public.opendatasoft.com/explore/dataset/liste-des-codes-postaux-belges-fr/table/?flg=fr
'''
postal_codes = pd.read_csv('./Datas/liste-des-codes-postaux-belges-fr.csv', sep=';')
postal_codes.head(10)

,Code postal,Localité,Sous-commune,Commune principale,Province
0,6810,Jamoigne,Oui,CHINY,Luxembourg
1,5589,Jemelle,NaN,NaN,NaN
2,3770,Kanne,Oui,RIEMST,Limbourg
3,3870,Klein-Gelmen,Oui,HEERS,Limbourg
4,3700,Koninksem,Oui,TONGEREN,Limbourg
5,2430,LAAKDAL,Non,LAAKDAL,Anvers
6,9280,LEBBEKE,Non,LEBBEKE,Flandre-Orientale
7,2890,Lippelo,Oui,PUURS-SINT-AMANDS,Anvers
8,6042,Lodelinsart,Oui,CHARLEROI,Hainaut
9,8570,ANZEGEM,Non,ANZEGEM,Flandre-Occidentale

In [22]:
# we only want to keep postal code and principal commune
commune_index = postal_codes[['Code postal', 'Commune principale']]
commune_index.head(10)

   Code postal Commune principale
0         6810              CHINY
1         5589                NaN
2         3770             RIEMST
3         3870              HEERS
4         3700           TONGEREN
5         2430            LAAKDAL
6         9280            LEBBEKE
7         2890  PUURS-SINT-AMANDS
8         6042          CHARLEROI
9         8570            ANZEGEM

In [23]:
commune_index = commune_index.copy()
commune_index.loc[1,'Commune principale'] = 'ROCHEFORT'
commune_index.loc[2763, 'Commune principale'] = 'SAINT-JOSSE-TEN-NOODE'
commune_index.loc[715, 'Commune principale'] = 'SAINT-JOSSE-TEN-NOODE'
commune_index.loc[748, 'Commune principale'] = 'SCHAERBEEK'
commune_index.loc[1389, 'Commune principale'] = 'SCHAERBEEK'
commune_index.loc[2744, 'Commune principale'] = 'SCHAERBEEK'

In [24]:
commune_index['Commune principale'].isna().sum()

38

In [25]:
'''mask = commune_index['Commune principale'].isna()
commune_index.loc[mask]'''

"mask = commune_index['Commune principale'].isna()\ncommune_index.loc[mask]"

In [26]:
commune_index.head(10)

   Code postal Commune principale
0         6810              CHINY
1         5589          ROCHEFORT
2         3770             RIEMST
3         3870              HEERS
4         3700           TONGEREN
5         2430            LAAKDAL
6         9280            LEBBEKE
7         2890  PUURS-SINT-AMANDS
8         6042          CHARLEROI
9         8570            ANZEGEM

In [27]:
commune_index.dropna(axis=0, inplace=True, subset=['Commune principale'])

In [28]:
commune_index['Commune principale'].isna().sum()

0

In [29]:
commune_index[commune_index['Code postal']==8957].index.values
commune_index.loc[2114]

Code postal               8957
Commune principale    MESSINES
Name: 2114, dtype: object

In [30]:
commune_index = commune_index.set_index('Code postal')
commune_index.head(5)

            Commune principale
Code postal
6810                     CHINY
5589                 ROCHEFORT
3770                    RIEMST
3870                     HEERS
3700                  TONGEREN

In [31]:
dict_commune = commune_index.to_dict()
dict_commune

{'Commune principale': {6810: 'CHINY',
  5589: 'ROCHEFORT',
  3770: 'RIEMST',
  3870: 'HEERS',
  3700: 'TONGEREN',
  2430: 'LAAKDAL',
  9280: 'LEBBEKE',
  2890: 'PUURS-SINT-AMANDS',
  6042: 'CHARLEROI',
  8570: 'ANZEGEM',
  3460: 'BEKKEVOORT',
  5580: 'ROCHEFORT',
  9690: 'KLUISBERGEN',
  6531: 'THUIN',
  4607: 'DALHEM',
  5021: 'NAMUR',
  5032: 'GEMBLOUX',
  6927: 'TELLIN',
  6743: 'ETALLE',
  5550: 'VRESSE-SUR-SEMOIS',
  7160: 'CHAPELLE-LEZ-HERLAIMONT',
  4537: 'VERLAINE',
  9170: 'SINT-GILLIS-WAAS',
  5310: 'EGHEZÉE',
  3740: 'BILZEN',
  9790: 'WORTEGEM-PETEGEM',
  4053: 'CHAUDFONTAINE',
  4800: 'VERVIERS',
  6441: 'FROIDCHAPELLE',
  7080: 'FRAMERIES',
  4347: 'FEXHE-LE-HAUT-CLOCHER',
  4181: 'HAMOIR',
  5650: 'WALCOURT',
  5651: 'WALCOURT',
  6940: 'DURBUY',
  3723: 'KORTESSEM',
  1320: 'BEAUVECHAIN',
  6767: 'ROUVROY',
  8340: 'DAMME',
  3471: 'KORTENAKEN',
  7110: 'LA LOUVIÈRE',
  8900: 'IEPER',
  1745: 'OPWIJK',
  6567: 'MERBES-LE-CHÂTEAU',
  4280: 'HANNUT',
  6780: 'MESSANCY',
  7942: 'BRUGELETTE',
  7070: 'LE ROEULX',
  5361: 'HAMOIS',
  3294: 'DIEST',
  1367: 'RAMILLIES',
  7812: 'ATH',
  2812: 'MECHELEN',
  3400: 'LANDEN',
  3850: 'NIEUWERKERKEN',
  8800: 'ROESELARE',
  5350: 'OHEY',
  3960: 'BREE',
  8582: 'AVELGEM',
  7134: 'BINCHE',
  8647: 'LO-RENINGE',
  4171: 'COMBLAIN-AU-PONT',
  6464: 'CHIMAY',
  8755: 'RUISELEDE',
  3803: 'SINT-TRUIDEN',
  5002: 'NAMUR',
  6982: 'LA ROCHE-EN-ARDENNE',
  9982: 'SINT-LAUREINS',
  2960: 'BRECHT',
  6470: 'SIVRY-RANCE',
  8433: 'MIDDELKERKE',
  5680: 'DOISCHE',
  1933: 'ZAVENTEM',
  6970: 'TENNEVILLE',
  2830: 'WILLEBROEK',
  4530: 'VILLERS-LE-BOUILLET',
  9130: 'BEVEREN-WAAS',
  6230: 'PONT-À-CELLES',
  6941: 'DURBUY',
  9800: 'DEINZE',
  7131: 'BINCHE',
  3830: 'WELLEN',
  3401: 'LANDEN',
  7370: 'DOUR',
  8980: 'ZONNEBEKE',
  9080: 'LOCHRISTI',
  8511: 'KORTRIJK',
  3200: 'AARSCHOT',
  5590: 'CINEY',
  6250: 'AISEAU-PRESLES',
  7640: 'ANTOING',
  7972: 'BELOEIL',
  7387: 'HONNELLES',
  6900: 'MARCHE-EN-FAMENNE',
  9111: 'SINT-NIKLAAS',
  4500: 'HUY',
  3581: 'BERINGEN',
  4690: 'BASSENGE',
  1404: 'NIVELLES',
  6850: 'PALISEUL',
  4987: 'STOUMONT',
  5022: 'NAMUR',
  7120: 'ESTINNES',
  5660: 'COUVIN',
  9160: 'LOKEREN',
  3440: 'ZOUTLEEUW',
  1620: 'DROGENBOS',
  1653: 'BEERSEL',
  1671: 'PEPINGEN',
  5530: 'YVOIR',
  6141: "FONTAINE-L'EVÊQUE",
  4557: 'TINLOT',
  3800: 'SINT-TRUIDEN',
  3890: 'GINGELOM',
  6534: 'THUIN',
  7950: 'CHIÈVRES',
  3945: 'HAM',
  7321: 'BERNISSART',
  5540: 'HASTIÈRE',
  1461: 'ITTRE',
  8301: 'KNOKKE-HEIST',
  9571: 'LIERDE',
  7090: 'BRAINE-LE-COMTE',
  3191: 'BOORTMEERBEEK',
  1560: 'HOEILAART',
  8377: 'ZUIENKERKE',
  9340: 'LEDE',
  1370: 'JODOIGNE',
  3010: 'LEUVEN',
  9050: 'GENT',
  1300: 'WAVRE',
  4710: 'LONTZEN',
  1471: 'GENAPPE',
  6593: 'MOMIGNIES',
  5330: 'ASSESSE',
  2390: 'MALLE',
  6987: 'RENDEUX',
  3630: 'MAASMECHELEN',
  2321: 'HOOGSTRATEN',
  9630: 'ZWALM',
  8930: 'MENEN',
  2170: 'ANTWERPEN',
  7000: 'MONS',
  9660: 'BRAKEL',
  3620: 'LANAKEN',
  3370: 'BOUTERSEM',
  5380: 'FERNELMONT',
  7743: 'PECQ',
  3300: 'TIENEN',
  8740: 'PITTEM',
  8920: 'LANGEMARK-POELKAPELLE',
  7040: 'QUÉVY',
  6043: 'CHARLEROI',
  1731: 'ASSE',
  6830: 'BOUILLON',
  7610: 'RUMES',
  7730: 'ESTAIMPUIS',
  4845: 'JALHAY',
  5070: 'FOSSES-LA-VILLE',
  3730: 'HOESELT',
  1600: 'SINT-PIETERS-LEEUW',
  6662: 'HOUFFALIZE',
  6840: 'NEUFCHÂTEAU',
  6890: 'LIBIN',
  7100: 'LA LOUVIÈRE',
  9290: 'BERLARE',
  4051: 'CHAUDFONTAINE',
  2431: 'LAAKDAL',
  9850: 'DEINZE',
  7390: 'QUAREGNON',
  2275: 'LILLE',
  1970: 'WEZEMBEEK-OPPEM',
  5570: 'BEAURAING',
  3722: 'KORTESSEM',
  8952: 'HEUVELLAND',
  9930: 'LIEVEGEM',
  8690: 'ALVERINGEM',
  6791: 'AUBANGE',
  8630: 'VEURNE',
  5640: 'METTET',
  1440: 'BRAINE-LE-CHÂTEAU',
  5300: 'ANDENNE',
  9450: 'HAALTERT',
  5537: 'ANHÉE',
  8792: 'WAREGEM',
  9042: 'GENT',
  3290: 'DIEST',
  2910: 'ESSEN',
  4631: 'SOUMAGNE',
  7170: 'MANAGE',
  3790: 'FOURONS',
  5150: 'FLOREFFE',
  4250: 'GEER',
  1755: 'GOOIK',
  3840: 'BORGLOON',
  6720: 'HABAY',
  5621: 'FLORENNES',
  1130: 'BRUXELLES',
  6960: 'MANHAY',
  5541: 'HASTIÈRE',
  5543: 'HASTIÈRE',
  1790: 'AFFLIGEM',
  3530: 'HOUTHALEN-HELCHTEREN',
  7830: 'SILLY',
  4650: 'HERVE',
  4671: 'BLÉGNY',
  8480: 'ICHTEGEM',
  8770: 'INGELMUNSTER',
  2560: 'NIJLEN',
  8610: 'KORTEMARK',
  8520: 'KUURNE',
  1380: 'LASNE',
  9030: 'GENT',
  1350: 'ORP-JAUCHE',
  2450: 'MEERHOUT',
  7822: 'ATH',
  8760: 'MEULEBEKE',
  7141: 'MORLANWELZ',
  6560: 'ERQUELINNES',
  4608: 'DALHEM',
  8620: 'NIEUWPOORT',
  6851: 'PALISEUL',
  9520: 'SINT-LIEVENS-HOUTEM',
  9420: 'ERPE-MERE',
  1340: 'OTTIGNIES-LOUVAIN-LA-NEUVE',
  9700: 'OUDENAARDE',
  3212: 'LUBBEEK',
  7600: 'PÉRUWELZ',
  8970: 'POPERINGE',
  4350: 'REMICOURT',
  6532: 'THUIN',
  4790: 'BURG-REULAND',
  7623: 'BRUNEHAUT',
  1760: 'ROOSDAAL',
  6747: 'SAINT-LÉGER',
  6730: 'TINTIGNY',
  5600: 'PHILIPPEVILLE',
  8700: 'TIELT',
  6832: 'BOUILLON',
  5630: 'CERFONTAINE',
  6640: 'VAUX-SUR-SÛRE',
  9980: 'SINT-LAUREINS',
  9667: 'HOREBEKE',
  2940: 'STABROEK',
  7618: 'RUMES',
  3390: 'TIELT-WINGE',
  1495: 'VILLERS-LA-VILLE',
  8902: 'IEPER',
  6224: 'FLEURUS',
  1410: 'WATERLOO',
  9988: 'SINT-LAUREINS',
  4860: 'PEPINSTER',
  2040: 'ANTWERPEN',
  3545: 'HALEN',
  9620: 'ZOTTEGEM',
  8904: 'IEPER',
  2380: 'RAVELS',
  1430: 'REBECQ',
  6210: 'LES BONS VILLERS',
  5575: 'GEDINNE',
  3732: 'HOESELT',
  9040: 'GENT',
  8470: 'GISTEL',
  6500: 'BEAUMONT',
  7500: 'TOURNAI',
  2300: 'TURNHOUT',
  3721: 'KORTESSEM',
  9400: 'NINOVE',
  4300: 'WAREMME',
  8940: 'WERVIK',
  2260: 'WESTERLO',
  3018: 'LEUVEN',
  8431: 'MIDDELKERKE',
  2160: 'WOMMELGEM',
  4550: 'NANDRIN',
  8400: 'OOSTENDE',
  5544: 'HASTIÈRE',
  2030: 'ANTWERPEN',
  7382: 'QUIÉVRAIN',
  3130: 'BEGIJNENDIJK',
  9881: 'AALTER',
  7903: 'LEUZE-EN-HAINAUT',
  4210: 'BURDINNE',
  5020: 'NAMUR',
  7063: 'SOIGNIES',
  6838: 'BOUILLON',
  8600: 'DIKSMUIDE',
  5363: 'HAMOIS',
  4480: 'ENGIS',
  6997: 'EREZÉE',
  5030: 'GEMBLOUX',
  5522: 'ONHAYE',
  7181: 'SENEFFE',
  7910: 'FRASNES-LEZ-ANVAING',
  2590: 'BERLAAR',
  5340: 'GESVES',
  1473: 'GENAPPE',
  6670: 'GOUVY',
  2980: 'ZOERSEL',
  2230: 'HERSELT',
  2540: 'HOVE',
  9472: 'DENDERLEEUW',
  7540: 'TOURNAI',
  4701: 'EUPEN',
  6238: 'PONT-À-CELLES',
  7810: 'ATH',
  3746: 'BILZEN',
  4101: 'SERAING',
  5190: 'JEMEPPE-SUR-SAMBRE',
  7620: 'BRUNEHAUT',
  2870: 'PUURS-SINT-AMANDS',
  5573: 'BEAURAING',
  3078: 'KORTENBERG',
  4770: 'AMBLÈVE',
  2400: 'MOL',
  7543: 'TOURNAI',
  6750: 'MUSSON',
  1357: 'HÉLÉCINE',
  3040: 'HULDENBERG',
  3668: 'AS',
  9100: 'SINT-NIKLAAS',
  3990: 'PEER',
  1670: 'PEPINGEN',
  9880: 'AALTER',
  2630: 'AARTSELAAR',
  1652: 'BEERSEL',
  2000: 'ANTWERPEN',
  9890: 'GAVERE',
  2387: 'BAARLE-HERTOG',
  5555: 'BIÈVRE',
  7130: 'BINCHE',
  6760: 'VIRTON',
  5170: 'PROFONDEVILLE',
  5004: 'NAMUR',
  4632: 'SOUMAGNE',
  6000: 'CHARLEROI',
  2180: 'ANTWERPEN',
  4750: 'BUTGENBACH',
  8830: 'HOOGLEDE',
  5353: 'OHEY',
  6698: 'VIELSALM',
  9120: 'BEVEREN-WAAS',
  1476: 'GENAPPE',
  8531: 'HARELBEKE',
  5060: 'SAMBREVILLE',
  9770: 'KRUISEM',
  4254: 'GEER',
  3560: 'LUMMEN',
  3350: 'LINTER',
  3680: 'MAASEIK',
  3971: 'LEOPOLDSBURG',
  8880: 'LEDEGEM',
  8860: 'LENDELEDE',
  5024: 'NAMUR',
  4219: 'WASSEIGES',
  9310: 'AALST',
  3272: 'SCHERPENHEUVEL-ZICHEM',
  3461: 'BEKKEVOORT',
  6674: 'GOUVY',
  9500: 'GERAARDSBERGEN',
  9860: 'OOSTERZELE',
  9200: 'DENDERMONDE',
  4287: 'LINCENT',
  6724: 'HABAY',
  1060: 'SAINT-GILLES',
  6820: 'FLORENVILLE',
  6740: 'ETALLE',
  2223: 'HEIST-OP-DEN-BERG',
  1750: 'LENNIK',
  9550: 'HERZELE',
  6769: 'MEIX-DEVANT-VIRTON',
  4630: 'SOUMAGNE',
  7901: 'LEUZE-EN-HAINAUT',
  7533: 'TOURNAI',
  1360: 'PERWEZ',
  1780: 'WEMMEL',
  8640: 'VLETEREN',
  5500: 'DINANT',
  2370: 'ARENDONK',
  1730: 'ASSE',
  4340: 'AWANS',
  1470: 'GENAPPE',
  1650: 'BEERSEL',
  1673: 'PEPINGEN',
  1082: 'BERCHEM-SAINTE-AGATHE',
  4960: 'MALMEDY',
  7604: 'PÉRUWELZ',
  5561: 'HOUYET',
  7033: 'MONS',
  1325: 'CHAUMONT-GISTOUX',
  7711: 'MOUSCRON',
  3650: 'DILSEN-STOKKEM',
  1040: 'ETTERBEEK',
  5560: 'HOUYET',
  7863: 'LESSINES',
  8691: 'ALVERINGEM',
  5620: 'FLORENNES',
  4540: 'AMAY',
  6280: 'GERPINNES',
  6040: 'CHARLEROI',
  3640: 'KINROOI',
  2500: 'LIER',
  1770: 'LIEDEKERKE',
  8958: 'HEUVELLAND',
  4920: 'AYWAILLE',
  6663: 'HOUFFALIZE',
  8720: 'DENTERGEM',
  7050: 'JURBISE',
  4041: 'HERSTAL',
  4400: 'FLÉMALLE',
  1435: 'MONT-SAINT-GUIBERT',
  6600: 'BASTOGNE',
  7804: 'ATH',
  6833: 'BOUILLON',
  5564: 'HOUYET',
  7340: 'COLFONTAINE',
  8978: 'POPERINGE',
  5100: 'NAMUR',
  4452: 'JUPRELLE',
  3012: 'LEUVEN',
  8750: 'WINGENE',
  2240: 'ZANDHOVEN',
  4761: 'BULLANGE',
  1210: 'SAINT-JOSSE-TEN-NOODE',
  7180: 'SENEFFE',
  9572: 'LIERDE',
  8490: 'JABBEKE',
  5646: 'METTET',
  6661: 'HOUFFALIZE',
  6530: 'THUIN',
  5362: 'HAMOIS',
  4601: 'VISÉ',
  3384: 'GLABBEEK',
  4560: 'CLAVIER',
  8583: 'AVELGEM',
  4020: 'LIÈGE',
  6536: 'THUIN',
  9320: 'AALST',
  8587: 'ESPIERRES-HELCHIN',
  6856: 'PALISEUL',
  4620: 'FLÉRON',
  3380: 'GLABBEEK',
  3450: 'GEETBETS',
  6986: 'LA ROCHE-EN-ARDENNE',
  3930: 'HAMONT-ACHEL',
  6990: 'HOTTON',
  5370: 'HAVELANGE',
  9070: 'DESTELBERGEN',
  4852: 'PLOMBIÈRES',
  2320: 'HOOGSTRATEN',
  2235: 'HULSHOUT',
  9970: 'KAPRIJKE',
  3472: 'KORTENAKEN',
  1020: 'BRUXELLES',
  4042: 'HERSTAL',
  7870: 'LENS',
  1840: 'LONDERZEEL',
  9920: 'LIEVEGEM',
  6591: 'MOMIGNIES',
  4420: 'SAINT-NICOLAS',
  9636: 'ZWALM',
  1390: 'GREZ-DOICEAU',
  1930: 'ZAVENTEM',
  5670: 'VIROINVAL',
  7601: 'PÉRUWELZ',
  1601: 'SINT-PIETERS-LEEUW',
  4672: 'BLÉGNY',
  1030: 'SCHAERBEEK',
  9820: 'MERELBEKE',
  5523: 'ONHAYE',
  3120: 'TREMELO',
  6690: 'VIELSALM',
  4260: 'BRAIVES',
  8421: 'DE HAAN',
  7548: 'TOURNAI',
  8790: 'WAREGEM',
  7890: 'ELLEZELLES',
  1980: 'ZEMST',
  1006: 'SAINT-JOSSE-TEN-NOODE',
  6460: 'CHIMAY',
  4130: 'ESNEUX',
  6700: 'ARLON',
  4870: 'TROOZ',
  1800: 'VILVOORDE',
  6461: 'CHIMAY',
  9506: 'GERAARDSBERGEN',
  4590: 'OUFFET',
  9473: 'DENDERLEEUW',
  4190: 'FERRIÈRES',
  8954: 'HEUVELLAND',
  2610: 'ANTWERPEN',
  9060: 'ZELZATE',
  9870: 'ZULTE',
  8550: 'ZWEVEGEM',
  1105: 'SCHAERBEEK',
  4031: 'LIÈGE',
  4837: 'BAELEN',
  5377: 'SOMME-LEUZE',
  6671: 'GOUVY',
  1450: 'CHASTRE',
  6673: 'GOUVY',
  4784: 'SAINT-VITH',
  8420: 'DE HAAN',
  8540: 'DEERLIJK',
  9831: 'SINT-MARTENS-LATEM',
  3941: 'HECHTEL-EKSEL',
  7850: 'ENGHIEN',
  7504: 'TOURNAI',
  6929: 'DAVERDISSE',
  1332: 'RIXENSART',
  5031: 'GEMBLOUX',
  7973: 'BELOEIL',
  3020: 'HERENT',
  4351: 'REMICOURT',
  3320: 'HOEGAARDEN',
  4520: 'WANZE',
  1315: 'INCOURT',
  7012: 'MONS',
  8650: 'HOUTHULST',
  4720: 'LA CALAMINE',
  6111: 'MONTIGNY-LE-TILLEUL',
  6811: 'CHINY',
  4990: 'LIERNEUX',
  1342: 'OTTIGNIES-LOUVAIN-LA-NEUVE',
  6688: 'BERTOGNE',
  7022: 'MONS',
  8552: 'ZWEVEGEM',
  6110: 'MONTIGNY-LE-TILLEUL',
  8890: 'MOORSLEDE',
  3891: 'GINGELOM',
  7034: 'MONS',
  3360: 'BIERBEEK',
  4680: 'OUPEYE',
  9401: 'NINOVE',
  7760: 'CELLES',
  2018: 'ANTWERPEN',
  9150: 'KRUIBEKE',
  9552: 'HERZELE',
  1420: "BRAINE-L'ALLEUD",
  1501: 'HALLE',
  1490: 'COURT-SAINT-ETIENNE',
  6972: 'TENNEVILLE',
  9940: 'EVERGEM',
  9680: 'MAARKEDAL',
  4317: 'FAIMES',
  1570: 'GALMAARDEN',
  4834: 'LIMBOURG',
  1702: 'DILBEEK',
  6950: 'NASSOGNE',
  3717: 'HERSTAPPE',
  1701: 'DILBEEK',
  8972: 'POPERINGE',
  1310: 'LA HULPE',
  6220: 'FLEURUS',
  4000: 'LIÈGE',
  5372: 'HAVELANGE',
  3391: 'TIELT-WINGE',
  9090: 'MELLE',
  6031: 'CHARLEROI',
  7350: 'HENSIES',
  4850: 'PLOMBIÈRES',
  9810: 'NAZARETH',
  5520: 'ONHAYE',
  3050: 'OUD-HEVERLEE',
  3381: 'GLABBEEK',
  6821: 'FLORENVILLE',
  1348: 'OTTIGNIES-LOUVAIN-LA-NEUVE',
  3202: 'AARSCHOT',
  9932: 'LIEVEGEM',
  8020: 'OOSTKAMP',
  6596: 'MOMIGNIES',
  7032: 'MONS',
  4970: 'STAVELOT',
  1402: 'NIVELLES',
  4263: 'BRAIVES',
  6741: 'ETALLE',
  2880: 'BORNEM',
  9260: 'WICHELEN',
  3670: 'OUDSBERGEN',
  3520: 'ZONHOVEN',
  1070: 'ANDERLECHT',
  3271: 'SCHERPENHEUVEL-ZICHEM',
  2490: 'BALEN',
  7534: 'TOURNAI',
  6543: 'LOBBES',
  8501: 'KORTRIJK',
  3190: 'BOORTMEERBEEK',
  4180: 'HAMOIR',
  8906: 'IEPER',
  5504: 'DINANT',
  6922: 'WELLIN',
  9992: 'MALDEGEM',
  6660: 'HOUFFALIZE',
  1910: 'KAMPENHOUT',
  7862: 'LESSINES',
  9968: 'ASSENEDE',
  8300: 'KNOKKE-HEIST',
  3511: 'HASSELT',
  6953: 'NASSOGNE',
  5080: 'LA BRUYÈRE',
  1640: 'RHODE-SAINT-GENÈSE',
  9688: 'MAARKEDAL',
  8710: 'WIELSBEKE',
  6813: 'CHINY',
  6680: 'SAINTE-ODE',
  4980: 'TROIS-PONTS',
  8370: 'BLANKENBERGE',
  8210: 'ZEDELGEM',
  1460: 'ITTRE',
  7971: 'BELOEIL',
  1741: 'TERNAT',
  7750: "MONT-DE-L'ENCLUS",
  7532: 'TOURNAI',
  2580: 'PUTTE',
  9961: 'ASSENEDE',
  5081: 'LA BRUYÈRE',
  4654: 'HERVE',
  4890: 'THIMISTER-CLERMONT',
  3590: 'DIEPENBEEK',
  7191: 'ECAUSSINNES',
  1190: 'FOREST',
  6440: 'FROIDCHAPELLE',
  6030: 'CHARLEROI',
  4030: 'LIÈGE',
  8560: 'WEVELGEM',
  6792: 'AUBANGE',
  1500: 'HALLE',
  2550: 'KONTICH',
  7622: 'BRUNEHAUT',
  1502: 'HALLE',
  3742: 'BILZEN',
  1820: 'STEENOKKERZEEL',
  7911: 'FRASNES-LEZ-ANVAING',
  5360: 'HAMOIS',
  7866: 'LESSINES',
  4252: 'GEER',
  6852: 'PALISEUL',
  4102: 'SERAING',
  3900: 'PELT',
  4600: 'VISÉ',
  1330: 'RIXENSART',
  1480: 'TUBIZE',
  3540: 'HERK-DE-STAD',
  3220: 'HOLSBEEK',
  4450: 'JUPRELLE',
  6182: 'COURCELLES',
  9190: 'STEKENE',
  3512: 'HASSELT',
  4577: 'MODAVE',
  6717: 'ATTERT',
  6462: 'CHIMAY',
  7538: 'TOURNAI',
  4453: 'JUPRELLE',
  3724: 'KORTESSEM',
  4711: 'LONTZEN',
  9840: 'DE PINTE',
  9051: 'GENT',
  6721: 'HABAY',
  3665: 'AS',
  7941: 'BRUGELETTE',
  8680: 'KOEKELARE',
  5336: 'ASSESSE',
  4218: 'HÉRON',
  1831: 'MACHELEN',
  5644: 'METTET',
  2440: 'GEEL',
  7041: 'QUÉVY',
  7900: 'LEUZE-EN-HAINAUT',
  3150: 'HAACHT',
  4730: 'RAEREN',
  7334: 'SAINT-GHISLAIN',
  2200: 'HERENTALS',
  4681: 'OUPEYE',
  2811: 'MECHELEN',
  2920: 'KALMTHOUT',
  9270: 'LAARNE',
  7522: 'TOURNAI',
  7621: 'BRUNEHAUT',
  9521: 'SINT-LIEVENS-HOUTEM',
  2845: 'NIEL',
  1400: 'NIVELLES',
  8730: 'BEERNEM',
  7861: 'LESSINES',
  4910: 'THEUX',
  6800: 'LIBRAMONT-CHEVIGNY',
  1742: 'TERNAT',
  2381: 'RAVELS',
  4160: 'ANTHISNES',
  2340: 'BEERSE',
  2820: 'BONHEIDEN',
  1761: 'ROOSDAAL',
  2520: 'RANST',
  1785: 'MERCHTEM',
  7602: 'PÉRUWELZ',
  4032: 'LIÈGE',
  4170: 'COMBLAIN-AU-PONT',
  6120: 'HAM-SUR-HEURE',
  9031: 'GENT',
  6637: 'FAUVILLERS',
  4367: 'CRISNÉE',
  5524: 'ONHAYE',
  4360: 'OREYE',
  2220: 'HEIST-OP-DEN-BERG',
  4802: 'VERVIERS',
  4162: 'ANTHISNES',
  2222: 'HEIST-OP-DEN-BERG',
  2950: 'KAPELLEN',
  3510: 'HASSELT',
  6860: 'LÉGLISE',
  1630: 'LINKEBEEK',
  4570: 'MARCHIN',
  6211: 'LES BONS VILLERS',
  9255: 'BUGGENHOUT',
  6240: 'FARCIENNES',
  4950: 'WAIMES',
  8820: 'TORHOUT',
  3832: 'WELLEN',
  7536: 'TOURNAI',
  3501: 'HASSELT',
  9240: 'ZELE',
  6870: 'SAINT-HUBERT',
  6951: 'NASSOGNE',
  4651: 'HERVE',
  6672: 'GOUVY',
  7970: 'BELOEIL',
  3060: 'BERTEM',
  6687: 'BERTOGNE',
  4670: 'BLÉGNY',
  5140: 'SOMBREFFE',
  7803: 'ATH',
  6742: 'ETALLE',
  6180: 'COURCELLES',
  6020: 'CHARLEROI',
  7912: 'FRASNES-LEZ-ANVAING',
  1700: 'DILBEEK',
  2570: 'DUFFEL',
  7190: 'ECAUSSINNES',
  4731: 'RAEREN',
  7943: 'BRUGELETTE',
  7906: 'LEUZE-EN-HAINAUT',
  6181: 'COURCELLES',
  4460: 'GRÂCE-HOLLOGNE',
  3053: 'OUD-HEVERLEE',
  8530: 'HARELBEKE',
  4771: 'AMBLÈVE',
  8956: 'HEUVELLAND',
  5101: 'NAMUR',
  6540: 'LOBBES',
  6924: 'WELLIN',
  5376: 'HAVELANGE',
  2322: 'HOOGSTRATEN',
  1035: 'SCHAERBEEK',
  1120: 'BRUXELLES',
  6880: 'BERTRIX',
  6044: 'CHARLEROI',
  4606: 'DALHEM',
  6887: 'HERBEUMONT',
  3470: 'KORTENAKEN',
  3980: 'TESSENDERLO',
  3793: 'FOURONS',
  4791: 'BURG-REULAND',
  7031: 'MONS',
  9950: 'LIEVEGEM',
  6223: 'FLEURUS',
  4217: 'HÉRON',
  8434: 'MIDDELKERKE',
  4621: 'FLÉRON',
  6150: 'ANDERLUES',
  4821: 'DISON',
  9404: 'NINOVE',
  4880: 'AUBEL',
  1160: 'AUDERGHEM',
  7331: 'SAINT-GHISLAIN',
  1401: 'NIVELLES',
  3580: 'BERINGEN',
  4831: 'LIMBOURG',
  8450: 'BREDENE',
  9140: 'TEMSE',
  6782: 'MESSANCY',
  5351: 'OHEY',
  8551: 'ZWEVEGEM',
  2801: 'MECHELEN',
  1654: 'BEERSEL',
  3061: 'BERTEM',
  7700: 'MOUSCRON',
  1860: 'MEISE',
  6592: 'MOMIGNIES',
  7542: 'TOURNAI',
  3221: 'HOLSBEEK',
  2242: 'ZANDHOVEN',
  2970: 'SCHILDE',
  2900: 'SCHOTEN',
  8554: 'ZWEVEGEM',
  6920: 'WELLIN',
  3080: 'TERVUREN',
  1180: 'UCCLE',
  9185: 'WACHTEBEKE',
  6666: 'HOUFFALIZE',
  7608: 'PÉRUWELZ',
  1861: 'MEISE',
  9960: 'ASSENEDE',
  3404: 'LANDEN',
  6824: 'FLORENVILLE',
  4820: 'DISON',
  4458: 'JUPRELLE',
  6140: "FONTAINE-L'EVÊQUE",
  7643: 'ANTOING',
  1083: 'GANSHOREN',
  7742: 'PECQ',
  3550: 'HEUSDEN-ZOLDER',
  3001: 'LEUVEN',
  2660: 'ANTWERPEN',
  7781: 'COMINES-WARNETON',
  3140: 'KEERBERGEN',
  9910: 'AALTER',
  8000: 'BRUGGE',
  6980: 'LA ROCHE-EN-ARDENNE',
  7860: 'LESSINES',
  4783: 'SAINT-VITH',
  4431: 'ANS',
  4623: 'FLÉRON',
  9402: 'NINOVE',
  8430: 'MIDDELKERKE',
  9220: 'HAMME',
  1080: 'MOLENBEEK-SAINT-JEAN',
  2250: 'OLEN',
  8840: 'STADEN',
  4122: 'NEUPRÉ',
  5574: 'BEAURAING',
  9551: 'HERZELE',
  2840: 'RUMST',
  8200: 'BRUGGE',
  6812: 'CHINY',
  3473: 'KORTENAKEN',
  2800: 'MECHELEN',
  8953: 'HEUVELLAND',
  3570: 'ALKEN',
  6790: 'AUBANGE',
  6706: 'ARLON',
  1674: 'PEPINGEN',
  4760: 'BULLANGE',
  8660: 'DE PANNE',
  9470: 'DENDERLEEUW',
  1982: 'ZEMST',
  8870: 'IZEGEM',
  5576: 'BEAURAING',
  9308: 'AALST',
  4140: 'SPRIMONT',
  6041: 'CHARLEROI',
  7801: 'ATH',
  1950: 'KRAAINEM',
  6142: "FONTAINE-L'EVÊQUE",
  1651: 'BEERSEL',
  5374: 'HAVELANGE',
  7062: 'SOIGNIES',
  4121: 'NEUPRÉ',
  4877: 'OLNE',
  8780: 'OOSTROZEBEKE',
  8460: 'OUDENBURG',
  9406: 'NINOVE',
  9600: 'RENAIX',
  3110: 'ROTSELAAR',
  4780: 'SAINT-VITH',
  7060: 'SOIGNIES',
  7951: 'CHIÈVRES',
  1602: 'SINT-PIETERS-LEEUW',
  8581: 'AVELGEM',
  9230: 'WETTEREN',
  8670: 'KOKSIJDE',
  2990: 'WUUSTWEZEL',
  7800: 'ATH',
  4983: 'TROIS-PONTS',
  8510: 'KORTRIJK',
  6834: 'BOUILLON',
  4257: 'BERLOZ',
  2530: 'BOECHOUT',
  2221: 'HEIST-OP-DEN-BERG',
  2930: 'BRASSCHAAT',
  6971: 'TENNEVILLE',
  6200: 'CHÂTELET',
  4253: 'GEER',
  3071: 'KORTENBERG',
  3600: 'GENK',
  3582: 'BERINGEN',
  3000: 'LEUVEN',
  9180: 'MOERBEKE-WAAS',
  8950: 'HEUVELLAND',
  6831: 'BOUILLON',
  7380: 'QUIÉVRAIN',
  7520: 'TOURNAI',
  3621: 'LANAKEN',
  4624: 'FLÉRON',
  9112: 'SINT-NIKLAAS',
  3500: 'HASSELT',
  8573: 'ANZEGEM',
  4161: 'ANTHISNES',
  2531: 'BOECHOUT',
  9772: 'KRUISEM',
  3831: 'WELLEN',
  1050: 'IXELLES',
  2140: 'ANTWERPEN',
  6222: 'FLEURUS',
  4050: 'CHAUDFONTAINE',
  4602: 'VISÉ',
  7780: 'COMINES-WARNETON',
  6010: 'CHARLEROI',
  5562: 'HOUYET',
  7864: 'LESSINES',
  6060: 'CHARLEROI',
  4841: 'WELKENRAEDT',
  1981: 'ZEMST',
  7301: 'BOUSSU',
  7624: 'BRUNEHAUT',
  3720: 'KORTESSEM',
  4357: 'DONCEEL',
  6001: 'CHARLEROI',
  1880: 'KAPELLE-OP-DEN-BOS',
  9041: 'GENT',
  9931: 'LIEVEGEM',
  1421: "BRAINE-L'ALLEUD",
  7802: 'ATH',
  8553: 'ZWEVEGEM',
  6221: 'FLEURUS',
  6781: 'MESSANCY',
  2860: 'SINT-KATELIJNE-WAVER',
  9981: 'SINT-LAUREINS',
  1541: 'HERNE',
  4900: 'SPA',
  3631: 'MAASMECHELEN',
  4652: 'HERVE',
  2050: 'ANTWERPEN',
  8580: 'AVELGEM',
  7320: 'BERNISSART',
  3950: 'BOCHOLT',
  4653: 'HERVE',
  5572: 'BEAURAING',
  7530: 'TOURNAI',
  2280: 'GROBBENDONK',
  6723: 'HABAY',
  7021: 'MONS',
  2620: 'HEMIKSEM',
  1540: 'HERNE',
  4682: 'OUPEYE',
  9750: 'KRUISEM',
  8810: 'LICHTERVELDE',
  2328: 'HOOGSTRATEN',
  2330: 'MERKSPLAS',
  9771: 'KRUISEM',
  3321: 'HOEGAARDEN',
  7322: 'BERNISSART',
  4610: 'BEYNE-HEUSAY',
  4120: 'NEUPRÉ',
  2460: 'KASTERLEE',
  9250: 'WAASMUNSTER',
  1170: 'WATERMAEL-BOITSFORT',
  7784: 'COMINES-WARNETON',
  1852: 'GRIMBERGEN',
  6533: 'THUIN',
  3052: 'OUD-HEVERLEE',
  1000: 'BRUXELLES',
  7061: 'SOIGNIES',
  2100: 'ANTWERPEN',
  8951: 'HEUVELLAND',
  8380: 'BRUGGE',
  3798: 'FOURONS',
  7712: 'MOUSCRON',
  4040: 'HERSTAL',
  5563: 'HOUYET',
  5354: 'OHEY',
  3293: 'DIEST',
  8851: 'ARDOOIE',
  6681: 'SAINTE-ODE',
  4141: 'SPRIMONT',
  8957: 'MESSINES',
  7332: 'SAINT-GHISLAIN',
  6983: 'LA ROCHE-EN-ARDENNE',
  2382: 'RAVELS',

In [32]:
# adding the commune feature to the base dataset
df['commune'] = [dict_commune['Commune principale'][pc] for pc in df['locality']]

In [33]:
df.commune.isnull().sum()

0

In [34]:
df[['commune','locality']].head(10)

               commune  locality
0              IXELLES      1050
1   KAPELLE-OP-DEN-BOS      1880
2                  SPA      4900
3  FRASNES-LEZ-ANVAING      7912
4            CHARLEROI      6032
5              BEERSEL      1650
6     CHAUMONT-GISTOUX      1325
7        CHAUDFONTAINE      4053
8            RIXENSART      1332
9               BRUGGE      8310

In [35]:
# order and rank the communes by price / m² 
commune_rank_dict = df.groupby('commune')['price_per_m²'].mean().sort_values().rank().to_dict()
commune_rank_dict

{'MOMIGNIES': 1.0,
 'SAINT-HUBERT': 2.0,
 'DOUR': 3.0,
 'HERSTAPPE': 4.0,
 'SAINTE-ODE': 5.0,
 'FAUVILLERS': 6.0,
 'COLFONTAINE': 7.0,
 'FLORENVILLE': 8.0,
 'SIVRY-RANCE': 9.0,
 'QUIÉVRAIN': 10.0,
 'VIROINVAL': 11.0,
 'QUAREGNON': 12.0,
 'TELLIN': 13.0,
 'CHÂTELET': 14.0,
 'ERQUELINNES': 15.0,
 'FARCIENNES': 16.0,
 'CERFONTAINE': 17.0,
 'BRUGELETTE': 18.0,
 'BIÈVRE': 19.0,
 'LIMBOURG': 20.0,
 'HONNELLES': 21.0,
 'ANDERLUES': 22.0,
 'BULLANGE': 23.0,
 'DOISCHE': 24.0,
 'ROUVROY': 25.0,
 'FLORENNES': 26.0,
 'BOUSSU': 27.0,
 'QUÉVY': 28.0,
 'CHIMAY': 29.0,
 'WALCOURT': 30.0,
 'PHILIPPEVILLE': 31.0,
 'BINCHE': 32.0,
 'COUVIN': 33.0,
 'MORLANWELZ': 34.0,
 'METTET': 35.0,
 'BEAUMONT': 36.0,
 'GEDINNE': 37.0,
 'FRAMERIES': 38.0,
 'PÉRUWELZ': 39.0,
 'CHINY': 40.0,
 'CHARLEROI': 41.0,
 'LA LOUVIÈRE': 42.0,
 'BERNISSART': 43.0,
 'COURCELLES': 44.0,
 'OREYE': 45.0,
 'ELLEZELLES': 46.0,
 'GINGELOM': 47.0,
 'VRESSE-SUR-SEMOIS': 48.0,
 'COMBLAIN-AU-PONT': 49.0,
 'HENSIES': 50.0,
 'MERBES-LE-CHÂTEAU': 51.0,
 'ANTOING': 52.0,
 'STAVELOT': 53.0,
 'FAIMES': 54.0,
 'BERTRIX': 55.0,
 'FLEURUS': 56.0,
 'VIRTON': 57.0,
 'BURG-REULAND': 58.0,
 "FONTAINE-L'EVÊQUE": 59.0,
 'HASTIÈRE': 60.0,
 'BOUILLON': 61.0,
 'HAVELANGE': 62.0,
 'OUFFET': 63.0,
 'SAINT-NICOLAS': 64.0,
 'HERBEUMONT': 65.0,
 'VAUX-SUR-SÛRE': 66.0,
 'PECQ': 67.0,
 'LE ROEULX': 68.0,
 'NEUFCHÂTEAU': 69.0,
 'DISON': 70.0,
 'LENS': 71.0,
 'HOESELT': 72.0,
 'ANTHISNES': 73.0,
 'VIELSALM': 74.0,
 'GOUVY': 75.0,
 'ENGIS': 76.0,
 'HOTTON': 77.0,
 'BEAURAING': 78.0,
 'PALISEUL': 79.0,
 'ESTINNES': 80.0,
 'FROIDCHAPELLE': 81.0,
 'ONHAYE': 82.0,
 'LO-RENINGE': 83.0,
 'BERTOGNE': 84.0,
 'BASSENGE': 85.0,
 'BELOEIL': 86.0,
 'DAVERDISSE': 87.0,
 'ANHÉE': 88.0,
 'RENDEUX': 89.0,
 'BUTGENBACH': 90.0,
 'PEPINSTER': 91.0,
 'MARCHIN': 92.0,
 'LESSINES': 93.0,
 'DINANT': 94.0,
 'MUSSON': 95.0,
 'CHAPELLE-LEZ-HERLAIMONT': 96.0,
 'SAINT-GEORGES-SUR-MEUSE': 97.0,
 'LEDEGEM': 98.0,
 'LEUZE-EN-HAINAUT': 99.0,
 'HAM-SUR-HEURE': 100.0,
 'HOUYET': 101.0,
 'GRÂCE-HOLLOGNE': 102.0,
 'OHEY': 103.0,
 'MONS': 104.0,
 'TINLOT': 105.0,
 'TROIS-PONTS': 106.0,
 'KINROOI': 107.0,
 'COMINES-WARNETON': 108.0,
 'WELLIN': 109.0,
 'PONT-À-CELLES': 110.0,
 'SAINT-GHISLAIN': 111.0,
 'LANGEMARK-POELKAPELLE': 112.0,
 'TENNEVILLE': 113.0,
 'MANAGE': 114.0,
 'NASSOGNE': 115.0,
 'DONCEEL': 116.0,
 'BRAKEL': 117.0,
 'ROCHEFORT': 118.0,
 'FLÉMALLE': 119.0,
 'HUY': 120.0,
 'SINT-LAUREINS': 121.0,
 'VERVIERS': 122.0,
 'HOUFFALIZE': 123.0,
 'SERAING': 124.0,
 'MOUSCRON': 125.0,
 'RAEREN': 126.0,
 'TINTIGNY': 127.0,
 'OLNE': 128.0,
 'BRUNEHAUT': 129.0,
 'AMBLÈVE': 130.0,
 'SOMME-LEUZE': 131.0,
 'MANHAY': 132.0,
 'RIEMST': 133.0,
 'HAM': 134.0,
 'CLAVIER': 135.0,
 'FOSSES-LA-VILLE': 136.0,
 'DILSEN-STOKKEM': 137.0,
 'LA ROCHE-EN-ARDENNE': 138.0,
 "MONT-DE-L'ENCLUS": 139.0,
 'MODAVE': 140.0,
 'ETALLE': 141.0,
 'SAMBREVILLE': 142.0,
 'AUBEL': 143.0,
 'EREZÉE': 144.0,
 'WAREMME': 145.0,
 'ASSESSE': 146.0,
 'FRASNES-LEZ-ANVAING': 147.0,
 'THUIN': 148.0,
 'MARCHE-EN-FAMENNE': 149.0,
 'JEMEPPE-SUR-SAMBRE': 150.0,
 'ESTAIMPUIS': 151.0,
 'TROOZ': 152.0,
 'ALVERINGEM': 153.0,
 'AISEAU-PRESLES': 154.0,
 'LOBBES': 155.0,
 'VLETEREN': 156.0,
 'STADEN': 157.0,
 'TOURNAI': 158.0,
 'MEIX-DEVANT-VIRTON': 159.0,
 'BALEN': 160.0,
 'VILLERS-LE-BOUILLET': 161.0,
 'ANS': 162.0,
 'BRAIVES': 163.0,
 'CHIÈVRES': 164.0,
 'LANDEN': 165.0,
 'LINTER': 166.0,
 'KLUISBERGEN': 167.0,
 'HAMOIR': 168.0,
 'LINCENT': 169.0,
 'BIÉVÈNE': 170.0,
 'LA CALAMINE': 171.0,
 'BURDINNE': 172.0,
 'HÉLÉCINE': 173.0,
 'MEERHOUT': 174.0,
 'VERLAINE': 175.0,
 'GERAARDSBERGEN': 176.0,
 'ORP-JAUCHE': 177.0,
 'AWANS': 178.0,
 'RUMES': 179.0,
 'HÉRON': 180.0,
 'FERRIÈRES': 181.0,
 'BILZEN': 182.0,
 'MENEN': 183.0,
 'HOUTHULST': 184.0,
 'FLOREFFE': 185.0,
 'WIELSBEKE': 186.0,
 'AMAY': 187.0,
 'THEUX': 188.0,
 'SOIGNIES': 189.0,
 'SOUMAGNE': 190.0,
 'WANZE': 191.0,
 'NANDRIN': 192.0,
 'MOORSLEDE': 193.0,
 'RENAIX': 194.0,
 'HERSTAL': 195.0,
 'BLÉGNY': 196.0,
 'BEYNE-HEUSAY': 197.0,
 'AS': 198.0,
 'OUPEYE': 199.0,
 'LIBIN': 200.0,
 'REMICOURT': 201.0,
 'HAMOIS': 202.0,
 'STOUMONT': 203.0,
 'KORTESSEM': 204.0,
 'GEETBETS': 205.0,
 'HALEN': 206.0,
 'MALMEDY': 207.0,
 'ZOUTLEEUW': 208.0,
 'ANDENNE': 209.0,
 'HERVE': 210.0,
 'KOEKELARE': 211.0,
 'SILLY': 212.0,
 'GEER': 213.0,
 'WERVIK': 214.0,
 'INCOURT': 215.0,
 'HABAY': 216.0,
 'AVELGEM': 217.0,
 'DALHEM': 218.0,
 'ATH': 219.0,
 'HEERS': 220.0,
 'FEXHE-LE-HAUT-CLOCHER': 221.0,
 'LA BRUYÈRE': 222.0,
 'SOMBREFFE': 223.0,
 'MAASEIK': 224.0,
 'VILLERS-LA-VILLE': 225.0,
 'REBECQ': 226.0,
 'ASSENEDE': 227.0,
 'ECAUSSINNES': 228.0,
 'HERK-DE-STAD': 229.0,
 'PEER': 230.0,
 'GERPINNES': 231.0,
 'RAVELS': 232.0,
 'ESPIERRES-HELCHIN': 233.0,
 'LIERDE': 234.0,
 'PITTEM': 235.0,
 'KORTENAKEN': 236.0,
 'HERZELE': 237.0,
 'EGHEZÉE': 238.0,
 'ZELE': 239.0,
 'LIÈGE': 240.0,
 'HOUTHALEN-HELCHTEREN': 241.0,
 'WAIMES': 242.0,
 'RAMILLIES': 243.0,
 'GESVES': 244.0,
 'LIBRAMONT-CHEVIGNY': 245.0,
 'TESSENDERLO': 246.0,
 'IZEGEM': 247.0,
 'FLÉRON': 248.0,
 'MEULEBEKE': 249.0,
 'WEVELGEM': 250.0,
 'OUD-TURNHOUT': 251.0,
 'LAAKDAL': 252.0,
 'MONTIGNY-LE-TILLEUL': 253.0,
 'YVOIR': 254.0,
 'MAASMECHELEN': 255.0,
 'LES BONS VILLERS': 256.0,
 'LEBBEKE': 257.0,
 'CELLES': 258.0,
 'SINT-GILLIS-WAAS': 259.0,
 'LENDELEDE': 260.0,
 'TUBIZE': 261.0,
 'VOSSELAAR': 262.0,
 'BORGLOON': 263.0,
 'AUBANGE': 264.0,
 'AYWAILLE': 265.0,
 'ENGHIEN': 266.0,
 'LEOPOLDSBURG': 267.0,
 'ZWEVEGEM': 268.0,
 'ICHTEGEM': 269.0,
 'MARTELANGE': 270.0,
 'FLOBECQ': 271.0,
 'FERNELMONT': 272.0,
 'VISÉ': 273.0,
 'BERLOZ': 274.0,
 'JODOIGNE': 275.0,
 'ZONHOVEN': 276.0,
 'WELKENRAEDT': 277.0,
 'ZELZATE': 278.0,
 'ZWALM': 279.0,
 'HERSELT': 280.0,
 'MERKSPLAS': 281.0,
 'SAINT-LÉGER': 282.0,
 'RETIE': 283.0,
 'HAMONT-ACHEL': 284.0,
 'LIEDEKERKE': 285.0,
 'THIMISTER-CLERMONT': 286.0,
 'KRUIBEKE': 287.0,
 'ARDOOIE': 288.0,
 'OUDENBURG': 289.0,
 'DIEST': 290.0,
 'WELLEN': 291.0,
 'CINEY': 292.0,
 'TONGEREN': 293.0,
 'LANAKEN': 294.0,
 'HEUVELLAND': 295.0,
 'FOURONS': 296.0,
 'DURBUY': 297.0,
 'DENTERGEM': 298.0,
 'PELT': 299.0,
 'MOL': 300.0,
 'BRAINE-LE-COMTE': 301.0,
 'TIENEN': 302.0,
 'BOCHOLT': 303.0,
 'WUUSTWEZEL': 304.0,
 'RUMST': 305.0,
 'DUFFEL': 306.0,
 'OLEN': 307.0,
 'LIERNEUX': 308.0,
 'BERINGEN': 309.0,
 'OOSTROZEBEKE': 310.0,
 'ROESELARE': 311.0,
 'KUURNE': 312.0,
 'PERWEZ': 313.0,
 'HANNUT': 314.0,
 'RIJKEVORSEL': 315.0,
 'WALHAIN': 316.0,
 'STEKENE': 317.0,
 'CHASTRE': 318.0,
 'BERLARE': 319.0,
 'SCHERPENHEUVEL-ZICHEM': 320.0,
 'PROFONDEVILLE': 321.0,
 'ERPE-MERE': 322.0,
 'JURBISE': 323.0,
 'ZULTE': 324.0,
 'BERLAAR': 325.0,
 'HARELBEKE': 326.0,
 'LONTZEN': 327.0,
 'PLOMBIÈRES': 328.0,
 'KORTEMARK': 329.0,
 'DESSEL': 330.0,
 'DENDERMONDE': 331.0,
 'WACHTEBEKE': 332.0,
 'SENEFFE': 333.0,
 'HULSHOUT': 334.0,
 'DENDERLEEUW': 335.0,
 'GALMAARDEN': 336.0,
 'LICHTERVELDE': 337.0,
 'SINT-TRUIDEN': 338.0,
 'VEURNE': 339.0,
 'HECHTEL-EKSEL': 340.0,
 'LÉGLISE': 341.0,
 'HEUSDEN-ZOLDER': 342.0,
 'MALDEGEM': 343.0,
 'BREE': 344.0,
 'DEERLIJK': 345.0,
 'HAALTERT': 346.0,
 'AFFLIGEM': 347.0,
 'MESSANCY': 348.0,
 'WESTERLO': 349.0,
 'DIKSMUIDE': 350.0,
 'SPRIMONT': 351.0,
 'AALST': 352.0,
 'JUPRELLE': 353.0,
 'ZOTTEGEM': 354.0,
 'BEAUVECHAIN': 355.0,
 'ANZEGEM': 356.0,
 'OUDSBERGEN': 357.0,
 'ARENDONK': 358.0,
 'BASTOGNE': 359.0,
 'NINOVE': 360.0,
 'ITTRE': 361.0,
 'CHAUDFONTAINE': 362.0,
 'WICHELEN': 363.0,
 'TEMSE': 364.0,
 'LILLE': 365.0,
 'BAELEN': 366.0,
 'OOSTKAMP': 367.0,
 'ZOERSEL': 368.0,
 'TORHOUT': 369.0,
 'GEEL': 370.0,
 'GLABBEEK': 371.0,
 'TREMELO': 372.0,
 'WINGENE': 373.0,
 'GROBBENDONK': 374.0,
 'NIEUWERKERKEN': 375.0,
 'STABROEK': 376.0,
 'BEGIJNENDIJK': 377.0,
 'GAVERE': 378.0,
 'WASSEIGES': 379.0,
 'LOMMEL': 380.0,
 'OPWIJK': 381.0,
 'GENAPPE': 382.0,
 'LUMMEN': 383.0,
 'HERNE': 384.0,
 'BEERNEM': 385.0,
 'NEUPRÉ': 386.0,
 'HAMME': 387.0,
 'WILLEBROEK': 388.0,
 'BOOM': 389.0,
 'JALHAY': 390.0,
 'OOSTERZELE': 391.0,
 'BEERSE': 392.0,
 'KORTRIJK': 393.0,
 'HOEGAARDEN': 394.0,
 'MORTSEL': 395.0,
 'WETTEREN': 396.0,
 'NIEL': 397.0,
 'BUGGENHOUT': 398.0,
 'DIEPENBEEK': 399.0,
 'MOLENBEEK-SAINT-JEAN': 400.0,
 'ZWIJNDRECHT': 401.0,
 'COURT-SAINT-ETIENNE': 402.0,
 'MAARKEDAL': 403.0,
 'HERENTALS': 404.0,
 'TURNHOUT': 405.0,
 'EEKLO': 406.0,
 'KRUISEM': 407.0,
 'AARSCHOT': 408.0,
 'NAMUR': 409.0,
 'ESSEN': 410.0,
 'SPA': 411.0,
 'HOREBEKE': 412.0,
 'LEDE': 413.0,
 'ZONNEBEKE': 414.0,
 'BEVEREN-WAAS': 415.0,
 'GOOIK': 416.0,
 'POPERINGE': 417.0,
 'OUDENAARDE': 418.0,
 'HEIST-OP-DEN-BERG': 419.0,
 'ALKEN': 420.0,
 'ATTERT': 421.0,
 'SCHELLE': 422.0,
 'LINT': 423.0,
 'EUPEN': 424.0,
 'EVERGEM': 425.0,
 'PUURS-SINT-AMANDS': 426.0,
 'LOKEREN': 427.0,
 'BRECHT': 428.0,
 'KASTERLEE': 429.0,
 'ESNEUX': 430.0,
 'HOOGLEDE': 431.0,
 'MOERBEKE-WAAS': 432.0,
 'NIVELLES': 433.0,
 'BOUTERSEM': 434.0,
 'ZEDELGEM': 435.0,
 'VORSELAAR': 436.0,
 'KAPELLE-OP-DEN-BOS': 437.0,
 'BRAINE-LE-CHÂTEAU': 438.0,
 'MALLE': 439.0,
 'SINT-LIEVENS-HOUTEM': 440.0,
 'CRISNÉE': 441.0,
 'SINT-NIKLAAS': 442.0,
 'GEMBLOUX': 443.0,
 'LIEVEGEM': 444.0,
 'ARLON': 445.0,
 'ZEMST': 446.0,
 'KAMPENHOUT': 447.0,
 'RUISELEDE': 448.0,
 'HAACHT': 449.0,
 'VILVOORDE': 450.0,
 'INGELMUNSTER': 451.0,
 'WAREGEM': 452.0,
 'BONHEIDEN': 453.0,
 'KAPRIJKE': 454.0,
 'KEERBERGEN': 455.0,
 'HEMIKSEM': 456.0,
 'SAINT-VITH': 457.0,
 'GENK': 458.0,
 'MELLE': 459.0,
 'PEPINGEN': 460.0,
 'BEKKEVOORT': 461.0,
 'ROOSDAAL': 462.0,
 'LIER': 463.0,
 'LONDERZEEL': 464.0,
 'KOEKELBERG': 465.0,
 'HOLSBEEK': 466.0,
 'LAARNE': 467.0,
 'RANST': 468.0,
 'TERNAT': 469.0,
 'BOORTMEERBEEK': 470.0,
 'WORTEGEM-PETEGEM': 471.0,
 'MEISE': 472.0,
 'KAPELLEN': 473.0,
 'BORSBEEK': 474.0,
 'SCHOTEN': 475.0,
 'ASSE': 476.0,
 'STEENOKKERZEEL': 477.0,
 'NIJLEN': 478.0,
 'HULDENBERG': 479.0,
 'OUD-HEVERLEE': 480.0,
 "BRAINE-L'ALLEUD": 481.0,
 'DAMME': 482.0,
 'WAVRE': 483.0,
 'GREZ-DOICEAU': 484.0,
 'WOMMELGEM': 485.0,
 'HALLE': 486.0,
 'SINT-PIETERS-LEEUW': 487.0,
 'BERTEM': 488.0,
 'AARTSELAAR': 489.0,
 'TIELT': 490.0,
 'BERCHEM-SAINTE-AGATHE': 491.0,
 'JABBEKE': 492.0,
 'HERENTHOUT': 493.0,
 'HASSELT': 494.0,
 'WIJNEGEM': 495.0,
 'KONTICH': 496.0,
 'SINT-KATELIJNE-WAVER': 497.0,
 'LOCHRISTI': 498.0,
 'BRASSCHAAT': 499.0,
 'LENNIK': 500.0,
 'PUTTE': 501.0,
 'BEERSEL': 502.0,
 'MECHELEN': 503.0,
 'ANDERLECHT': 504.0,
 'AALTER': 505.0,
 'GISTEL': 506.0,
 'LUBBEEK': 507.0,
 'SCHILDE': 508.0,
 'BREDENE': 509.0,
 'HOOGSTRATEN': 510.0,
 'HERENT': 511.0,
 'CHAUMONT-GISTOUX': 512.0,
 'JETTE': 513.0,
 'TIELT-WINGE': 514.0,
 'KORTENBERG': 515.0,
 'GRIMBERGEN': 516.0,
 'GANSHOREN': 517.0,
 'EDEGEM': 518.0,
 'DILBEEK': 519.0,
 'ROTSELAAR': 520.0,
 'ZANDHOVEN': 521.0,
 'LINKEBEEK': 522.0,
 'HOEILAART': 523.0,
 'BORNEM': 524.0,
 'DEINZE': 525.0,
 'WEMMEL': 526.0,
 'BIERBEEK': 527.0,
 'ZUTENDAAL': 528.0,
 'NAZARETH': 529.0,
 'KALMTHOUT': 530.0,
 'MERCHTEM': 531.0,
 'ANTWERPEN': 532.0,
 'BOECHOUT': 533.0,
 'ZUIENKERKE': 534.0,
 'MONT-SAINT-GUIBERT': 535.0,
 'SAINT-JOSSE-TEN-NOODE': 536.0,
 'MERELBEKE': 537.0,
 'DROGENBOS': 538.0,
 'OVERIJSE': 539.0,
 'SCHAERBEEK': 540.0,
 'WAASMUNSTER': 541.0,
 'IEPER': 542.0,
 'DE PANNE': 543.0,
 'DESTELBERGEN': 544.0,
 'BLANKENBERGE': 545.0,
 'DE PINTE': 546.0,
 'LASNE': 547.0,
 'BAARLE-HERTOG': 548.0,
 'HOVE': 549.0,
 'FOREST': 550.0,
 'TERVUREN': 551.0,
 'RHODE-SAINT-GENÈSE': 552.0,
 'EVERE': 553.0,
 'OOSTENDE': 554.0,
 'ZAVENTEM': 555.0,
 'BRUGGE': 556.0,
 'MACHELEN': 557.0,
 'RIXENSART': 558.0,
 'WATERLOO': 559.0,
 'LA HULPE': 560.0,
 'SINT-MARTENS-LATEM': 561.0,
 'MIDDELKERKE': 562.0,
 'DE HAAN': 563.0,
 'GENT': 564.0,
 'OTTIGNIES-LOUVAIN-LA-NEUVE': 565.0,
 'SAINT-GILLES': 566.0,
 'BRUXELLES': 567.0,
 'WATERMAEL-BOITSFORT': 568.0,
 'WEZEMBEEK-OPPEM': 569.0,
 'WOLUWE-SAINT-LAMBERT': 570.0,
 'KRAAINEM': 571.0,
 'UCCLE': 572.0,
 'KOKSIJDE': 573.0,
 'WOLUWE-SAINT-PIERRE': 574.0,
 'ETTERBEEK': 575.0,
 'NIEUWPOORT': 576.0,
 'AUDERGHEM': 577.0,
 'IXELLES': 578.0,
 'LEUVEN': 579.0,
 'KNOKKE-HEIST': 580.0}

In [37]:
# save the dict to use it in the API 
import csv

dict_to_save = commune_rank_dict
w = csv.writer(open("./Datas/commune_rank.csv", "w"))
for key, val in dict_to_save.items():
    w.writerow([key, val])

In [38]:
# add rank_commune to the base dataset 
df['rank_commune'] = [commune_rank_dict[commune_name] for commune_name in df['commune']]

In [52]:
df

,type_of_property,subtype_of_property,locality,province,région,price,number_of_facades,house_area,house_area_cat,number_of_rooms,...,terrace,terrace_area,open_fire,swimming_pool,state_of_the_building,construction_year,construction_year_cat,price_per_m²,commune,rank_commune
0,house,house,1050,Bruxelles-Capitale,Région Bruxelles-capitale,340000,2.0,203.0,]180-240 m²],6,...,1,NaN,0,0,to be done up,1901.0,1900-1919,1674.88,IXELLES,578.0
1,house,villa,1880,Brabant flamand,Région flamande,525000,4.0,250.0,]240m²- ],6,...,1,40.0,0,0,as new,1992.0,1980-1999,2100.00,KAPELLE-OP-DEN-BOS,437.0
2,house,exceptional property,4900,Liège,Région wallonne,550000,4.0,475.0,]240m²- ],11,...,1,NaN,0,0,good,1853.0,older than 1900,1157.89,SPA,411.0
3,house,villa,7912,Hainaut,Région wallonne,550000,4.0,325.0,]240m²- ],4,...,1,NaN,0,0,good,1918.0,1900-1919,1692.31,FRASNES-LEZ-ANVAING,147.0
4,house,house,6032,Hainaut,Région wallonne,550000,3.0,400.0,]240m²- ],5,...,1,80.0,0,0,as new,1977.0,1960-1979,1375.00,CHARLEROI,41.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42347,house,house,2310,Anvers,Région flamande,468000,4.0,180.0,]120-180 m²],3,...,0,NaN,0,0,NaN,NaN,NaN,2600.00,RIJKEVORSEL,315.0
42348,house,house,1800,Brabant flamand,Région flamande,454993,3.0,169.0,]120-180 m²],3,...,0,NaN,0,0,NaN,NaN,NaN,2692.27,VILVOORDE,450.0
42349,house,villa,3530,Limbourg,Région flamande,475000,4.0,222.0,]180-240 m²],3,...,0,NaN,0,0,NaN,NaN,NaN,2139.64,HOUTHALEN-HELCHTEREN,241.0
42350,house,mansion,6700,Luxembourg,Région wallonne,475000,2.0,240.0,]180-240 m²],9,...,0,NaN,0,0,NaN,NaN,NaN,1979.17,ARLON,445.0
42351,house,house,2018,Anvers,Région flamande,488000,3.0,145.0,]120-180 m²],3,...,0,NaN,0,0,NaN,NaN,NaN,3365.52,ANTWERPEN,532.0

### Finally , Split the dataset between houses and apartments

In [53]:
# Seperate the house from the base dataset
df_house = df[df['type_of_property']=='house']
df_house.reset_index(drop=True, inplace=True)

# Save the house dataset in a csv
df_house.to_csv('./Datas/dataset_house.csv')
df_house

,type_of_property,subtype_of_property,locality,province,région,price,number_of_facades,house_area,house_area_cat,number_of_rooms,...,terrace,terrace_area,open_fire,swimming_pool,state_of_the_building,construction_year,construction_year_cat,price_per_m²,commune,rank_commune
0,house,house,1050,Bruxelles-Capitale,Région Bruxelles-capitale,340000,2.0,203.0,]180-240 m²],6,...,1,NaN,0,0,to be done up,1901.0,1900-1919,1674.88,IXELLES,578.0
1,house,villa,1880,Brabant flamand,Région flamande,525000,4.0,250.0,]240m²- ],6,...,1,40.0,0,0,as new,1992.0,1980-1999,2100.00,KAPELLE-OP-DEN-BOS,437.0
2,house,exceptional property,4900,Liège,Région wallonne,550000,4.0,475.0,]240m²- ],11,...,1,NaN,0,0,good,1853.0,older than 1900,1157.89,SPA,411.0
3,house,villa,7912,Hainaut,Région wallonne,550000,4.0,325.0,]240m²- ],4,...,1,NaN,0,0,good,1918.0,1900-1919,1692.31,FRASNES-LEZ-ANVAING,147.0
4,house,house,6032,Hainaut,Région wallonne,550000,3.0,400.0,]240m²- ],5,...,1,80.0,0,0,as new,1977.0,1960-1979,1375.00,CHARLEROI,41.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22217,house,house,2310,Anvers,Région flamande,468000,4.0,180.0,]120-180 m²],3,...,0,NaN,0,0,NaN,NaN,NaN,2600.00,RIJKEVORSEL,315.0
22218,house,house,1800,Brabant flamand,Région flamande,454993,3.0,169.0,]120-180 m²],3,...,0,NaN,0,0,NaN,NaN,NaN,2692.27,VILVOORDE,450.0
22219,house,villa,3530,Limbourg,Région flamande,475000,4.0,222.0,]180-240 m²],3,...,0,NaN,0,0,NaN,NaN,NaN,2139.64,HOUTHALEN-HELCHTEREN,241.0
22220,house,mansion,6700,Luxembourg,Région wallonne,475000,2.0,240.0,]180-240 m²],9,...,0,NaN,0,0,NaN,NaN,NaN,1979.17,ARLON,445.0
22221,house,house,2018,Anvers,Région flamande,488000,3.0,145.0,]120-180 m²],3,...,0,NaN,0,0,NaN,NaN,NaN,3365.52,ANTWERPEN,532.0

In [54]:
# Seperate the house from the base dataset
df_apartment = df[df['type_of_property']=='apartment']
df_apartment.reset_index(drop=True, inplace=True)

# Save the apartment dataset in a csv
df_apartment.to_csv('./Datas/dataset_apartment.csv')
df_apartment

,type_of_property,subtype_of_property,locality,province,région,price,number_of_facades,house_area,house_area_cat,number_of_rooms,...,terrace,terrace_area,open_fire,swimming_pool,state_of_the_building,construction_year,construction_year_cat,price_per_m²,commune,rank_commune
0,apartment,apartment,4000,Liège,Région wallonne,45000,2.0,47.0,[0-60 m²],1,...,1,2.0,0,0,good,1958.0,1940-1959,957.45,LIÈGE,240.0
1,apartment,apartment,1030,Bruxelles-Capitale,Région Bruxelles-capitale,50000,NaN,96.0,]60-120 m²],2,...,0,NaN,0,0,good,1960.0,1960-1979,520.83,SCHAERBEEK,540.0
2,apartment,service flat,2930,Anvers,Région flamande,50000,3.0,83.0,]60-120 m²],2,...,1,NaN,0,0,NaN,2016.0,2000-,602.41,BRASSCHAAT,499.0
3,apartment,apartment,8420,Flandre-Occidentale,Région flamande,49500,2.0,31.0,[0-60 m²],1,...,0,NaN,0,0,good,1966.0,1960-1979,1596.77,DE HAAN,563.0
4,apartment,apartment,7301,Hainaut,Région wallonne,50000,2.0,49.0,[0-60 m²],1,...,0,NaN,0,0,NaN,NaN,NaN,1020.41,BOUSSU,27.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19831,apartment,apartment,8300,Flandre-Occidentale,Région flamande,950000,2.0,157.0,]120-180 m²],2,...,0,NaN,0,0,good,NaN,NaN,6050.96,KNOKKE-HEIST,580.0
19832,apartment,penthouse,3700,Limbourg,Région flamande,945000,NaN,164.0,]120-180 m²],3,...,0,NaN,0,0,as new,NaN,NaN,5762.20,TONGEREN,293.0
19833,apartment,apartment,6940,Luxembourg,Région wallonne,950000,NaN,111.0,]60-120 m²],2,...,1,115.0,0,0,NaN,2020.0,2000-,8558.56,DURBUY,297.0
19834,apartment,ground floor,8000,Flandre-Occidentale,Région flamande,950000,NaN,182.0,]180-240 m²],2,...,0,NaN,0,0,just renovated,NaN,NaN,5219.78,BRUGGE,556.0
19835,apartment,apartment,9050,Flandre-Orientale,Région flamande,295000,4.0,79.0,]60-120 m²],2,...,1,NaN,0,0,good,NaN,NaN,3734.18,GENT,564.0